//************************************************************************************
//*                                                                                  *
//* ===== DO NOT EDIT =====                                                          *
//* Any change will be overwritten                                                   *
//* Generated by github.com/boundedinfinity/enumer                                   *
//*                                                                                  *
//************************************************************************************

package mime_type

import (
	"encoding/json"
	"errors"
	"fmt"
	"strings"
)

type MimeType string
type MimeTypes []MimeType

func Slice(es ...MimeType) MimeTypes {
	var s MimeTypes

	for _, e := range es {
		s = append(s, e)
	}

	return s
}

const (
	ApplicationAndrewInset                                               MimeType = "application/andrew-inset"
	ApplicationApplixware                                                MimeType = "application/applixware"
	ApplicationAtomXml                                                   MimeType = "application/atom+xml"
	ApplicationAtomcatXml                                                MimeType = "application/atomcat+xml"
	ApplicationAtomsvcXml                                                MimeType = "application/atomsvc+xml"
	ApplicationCcxmlXml                                                  MimeType = "application/ccxml+xml"
	ApplicationCdmiCapability                                            MimeType = "application/cdmi-capability"
	ApplicationCdmiContainer                                             MimeType = "application/cdmi-container"
	ApplicationCdmiDomain                                                MimeType = "application/cdmi-domain"
	ApplicationCdmiObject                                                MimeType = "application/cdmi-object"
	ApplicationCdmiQueue                                                 MimeType = "application/cdmi-queue"
	ApplicationCuSeeme                                                   MimeType = "application/cu-seeme"
	ApplicationDavmountXml                                               MimeType = "application/davmount+xml"
	ApplicationDsscDer                                                   MimeType = "application/dssc+der"
	ApplicationDsscXml                                                   MimeType = "application/dssc+xml"
	ApplicationEcmascript                                                MimeType = "application/ecmascript"
	ApplicationEmmaXml                                                   MimeType = "application/emma+xml"
	ApplicationEpubZip                                                   MimeType = "application/epub+zip"
	ApplicationExi                                                       MimeType = "application/exi"
	ApplicationFontTdpfr                                                 MimeType = "application/font-tdpfr"
	ApplicationGpxXml                                                    MimeType = "application/gpx+xml"
	ApplicationGzip                                                      MimeType = "application/gzip"
	ApplicationHyperstudio                                               MimeType = "application/hyperstudio"
	ApplicationIpfix                                                     MimeType = "application/ipfix"
	ApplicationJavaArchive                                               MimeType = "application/java-archive"
	ApplicationJavaSerializedObject                                      MimeType = "application/java-serialized-object"
	ApplicationJavaVm                                                    MimeType = "application/java-vm"
	ApplicationJavascript                                                MimeType = "application/javascript"
	ApplicationJson                                                      MimeType = "application/json"
	ApplicationLdJson                                                    MimeType = "application/ld+json"
	ApplicationMacBinhex40                                               MimeType = "application/mac-binhex40"
	ApplicationMacCompactpro                                             MimeType = "application/mac-compactpro"
	ApplicationMadsXml                                                   MimeType = "application/mads+xml"
	ApplicationMarc                                                      MimeType = "application/marc"
	ApplicationMarcxmlXml                                                MimeType = "application/marcxml+xml"
	ApplicationMathematica                                               MimeType = "application/mathematica"
	ApplicationMathmlXml                                                 MimeType = "application/mathml+xml"
	ApplicationMbox                                                      MimeType = "application/mbox"
	ApplicationMediaservercontrolXml                                     MimeType = "application/mediaservercontrol+xml"
	ApplicationMetalink4Xml                                              MimeType = "application/metalink4+xml"
	ApplicationMetsXml                                                   MimeType = "application/mets+xml"
	ApplicationModsXml                                                   MimeType = "application/mods+xml"
	ApplicationMp21                                                      MimeType = "application/mp21"
	ApplicationMp4                                                       MimeType = "application/mp4"
	ApplicationMsword                                                    MimeType = "application/msword"
	ApplicationMxf                                                       MimeType = "application/mxf"
	ApplicationOctetStream                                               MimeType = "application/octet-stream"
	ApplicationOda                                                       MimeType = "application/oda"
	ApplicationOebpsPackageXml                                           MimeType = "application/oebps-package+xml"
	ApplicationOgg                                                       MimeType = "application/ogg"
	ApplicationOnenote                                                   MimeType = "application/onenote"
	ApplicationPatchOpsErrorXml                                          MimeType = "application/patch-ops-error+xml"
	ApplicationPdf                                                       MimeType = "application/pdf"
	ApplicationPgpEncrypted                                              MimeType = "application/pgp-encrypted"
	ApplicationPgpSignature                                              MimeType = "application/pgp-signature"
	ApplicationPicsRules                                                 MimeType = "application/pics-rules"
	ApplicationPkcs10                                                    MimeType = "application/pkcs10"
	ApplicationPkcs7Mime                                                 MimeType = "application/pkcs7-mime"
	ApplicationPkcs7Signature                                            MimeType = "application/pkcs7-signature"
	ApplicationPkcs8                                                     MimeType = "application/pkcs8"
	ApplicationPkixAttrCert                                              MimeType = "application/pkix-attr-cert"
	ApplicationPkixCert                                                  MimeType = "application/pkix-cert"
	ApplicationPkixCrl                                                   MimeType = "application/pkix-crl"
	ApplicationPkixPkipath                                               MimeType = "application/pkix-pkipath"
	ApplicationPkixcmp                                                   MimeType = "application/pkixcmp"
	ApplicationPlsXml                                                    MimeType = "application/pls+xml"
	ApplicationPostscript                                                MimeType = "application/postscript"
	ApplicationPrsCww                                                    MimeType = "application/prs.cww"
	ApplicationPskcXml                                                   MimeType = "application/pskc+xml"
	ApplicationRdfXml                                                    MimeType = "application/rdf+xml"
	ApplicationReginfoXml                                                MimeType = "application/reginfo+xml"
	ApplicationRelaxNgCompactSyntax                                      MimeType = "application/relax-ng-compact-syntax"
	ApplicationResourceListsDiffXml                                      MimeType = "application/resource-lists-diff+xml"
	ApplicationResourceListsXml                                          MimeType = "application/resource-lists+xml"
	ApplicationRlsServicesXml                                            MimeType = "application/rls-services+xml"
	ApplicationRsdXml                                                    MimeType = "application/rsd+xml"
	ApplicationRssXml                                                    MimeType = "application/rss+xml"
	ApplicationRtf                                                       MimeType = "application/rtf"
	ApplicationSbmlXml                                                   MimeType = "application/sbml+xml"
	ApplicationScvpCvRequest                                             MimeType = "application/scvp-cv-request"
	ApplicationScvpCvResponse                                            MimeType = "application/scvp-cv-response"
	ApplicationScvpVpRequest                                             MimeType = "application/scvp-vp-request"
	ApplicationScvpVpResponse                                            MimeType = "application/scvp-vp-response"
	ApplicationSdp                                                       MimeType = "application/sdp"
	ApplicationSetPaymentInitiation                                      MimeType = "application/set-payment-initiation"
	ApplicationSetRegistrationInitiation                                 MimeType = "application/set-registration-initiation"
	ApplicationShfXml                                                    MimeType = "application/shf+xml"
	ApplicationSmilXml                                                   MimeType = "application/smil+xml"
	ApplicationSparqlQuery                                               MimeType = "application/sparql-query"
	ApplicationSparqlResultsXml                                          MimeType = "application/sparql-results+xml"
	ApplicationSrgs                                                      MimeType = "application/srgs"
	ApplicationSrgsXml                                                   MimeType = "application/srgs+xml"
	ApplicationSruXml                                                    MimeType = "application/sru+xml"
	ApplicationSsmlXml                                                   MimeType = "application/ssml+xml"
	ApplicationTeiXml                                                    MimeType = "application/tei+xml"
	ApplicationThraudXml                                                 MimeType = "application/thraud+xml"
	ApplicationTimestampedData                                           MimeType = "application/timestamped-data"
	ApplicationVnd3gpp2Tcap                                              MimeType = "application/vnd.3gpp2.tcap"
	ApplicationVnd3gppPicBwLarge                                         MimeType = "application/vnd.3gpp.pic-bw-large"
	ApplicationVnd3gppPicBwSmall                                         MimeType = "application/vnd.3gpp.pic-bw-small"
	ApplicationVnd3gppPicBwVar                                           MimeType = "application/vnd.3gpp.pic-bw-var"
	ApplicationVnd3mPostItNotes                                          MimeType = "application/vnd.3m.post-it-notes"
	ApplicationVndAccpacSimplyAso                                        MimeType = "application/vnd.accpac.simply.aso"
	ApplicationVndAccpacSimplyImp                                        MimeType = "application/vnd.accpac.simply.imp"
	ApplicationVndAcucobol                                               MimeType = "application/vnd.acucobol"
	ApplicationVndAcucorp                                                MimeType = "application/vnd.acucorp"
	ApplicationVndAdobeAirApplicationInstallerPackageZip                 MimeType = "application/vnd.adobe.air-application-installer-package+zip"
	ApplicationVndAdobeFxp                                               MimeType = "application/vnd.adobe.fxp"
	ApplicationVndAdobeXdpXml                                            MimeType = "application/vnd.adobe.xdp+xml"
	ApplicationVndAdobeXfdf                                              MimeType = "application/vnd.adobe.xfdf"
	ApplicationVndAheadSpace                                             MimeType = "application/vnd.ahead.space"
	ApplicationVndAirzipFilesecureAzf                                    MimeType = "application/vnd.airzip.filesecure.azf"
	ApplicationVndAirzipFilesecureAzs                                    MimeType = "application/vnd.airzip.filesecure.azs"
	ApplicationVndAmazonEbook                                            MimeType = "application/vnd.amazon.ebook"
	ApplicationVndAmericandynamicsAcc                                    MimeType = "application/vnd.americandynamics.acc"
	ApplicationVndAmigaAmi                                               MimeType = "application/vnd.amiga.ami"
	ApplicationVndAndroidPackageArchive                                  MimeType = "application/vnd.android.package-archive"
	ApplicationVndAnserWebCertificateIssueInitiation                     MimeType = "application/vnd.anser-web-certificate-issue-initiation"
	ApplicationVndAnserWebFundsTransferInitiation                        MimeType = "application/vnd.anser-web-funds-transfer-initiation"
	ApplicationVndAntixGameComponent                                     MimeType = "application/vnd.antix.game-component"
	ApplicationVndAppleInstallerXml                                      MimeType = "application/vnd.apple.installer+xml"
	ApplicationVndAppleMpegurl                                           MimeType = "application/vnd.apple.mpegurl"
	ApplicationVndAristanetworksSwi                                      MimeType = "application/vnd.aristanetworks.swi"
	ApplicationVndAudiograph                                             MimeType = "application/vnd.audiograph"
	ApplicationVndBlueiceMultipass                                       MimeType = "application/vnd.blueice.multipass"
	ApplicationVndBmi                                                    MimeType = "application/vnd.bmi"
	ApplicationVndBusinessobjects                                        MimeType = "application/vnd.businessobjects"
	ApplicationVndChemdrawXml                                            MimeType = "application/vnd.chemdraw+xml"
	ApplicationVndChipnutsKaraokeMmd                                     MimeType = "application/vnd.chipnuts.karaoke-mmd"
	ApplicationVndCinderella                                             MimeType = "application/vnd.cinderella"
	ApplicationVndClaymore                                               MimeType = "application/vnd.claymore"
	ApplicationVndCloantoRp9                                             MimeType = "application/vnd.cloanto.rp9"
	ApplicationVndClonkC4group                                           MimeType = "application/vnd.clonk.c4group"
	ApplicationVndCluetrustCartomobileConfig                             MimeType = "application/vnd.cluetrust.cartomobile-config"
	ApplicationVndCluetrustCartomobileConfigPkg                          MimeType = "application/vnd.cluetrust.cartomobile-config-pkg"
	ApplicationVndCommonspace                                            MimeType = "application/vnd.commonspace"
	ApplicationVndContactCmsg                                            MimeType = "application/vnd.contact.cmsg"
	ApplicationVndCosmocaller                                            MimeType = "application/vnd.cosmocaller"
	ApplicationVndCrickClicker                                           MimeType = "application/vnd.crick.clicker"
	ApplicationVndCrickClickerKeyboard                                   MimeType = "application/vnd.crick.clicker.keyboard"
	ApplicationVndCrickClickerPalette                                    MimeType = "application/vnd.crick.clicker.palette"
	ApplicationVndCrickClickerTemplate                                   MimeType = "application/vnd.crick.clicker.template"
	ApplicationVndCrickClickerWordbank                                   MimeType = "application/vnd.crick.clicker.wordbank"
	ApplicationVndCriticaltoolsWbsXml                                    MimeType = "application/vnd.criticaltools.wbs+xml"
	ApplicationVndCtcPosml                                               MimeType = "application/vnd.ctc-posml"
	ApplicationVndCupsPpd                                                MimeType = "application/vnd.cups-ppd"
	ApplicationVndCurlCar                                                MimeType = "application/vnd.curl.car"
	ApplicationVndCurlPcurl                                              MimeType = "application/vnd.curl.pcurl"
	ApplicationVndDataVisionRdz                                          MimeType = "application/vnd.data-vision.rdz"
	ApplicationVndDenovoFcselayoutLink                                   MimeType = "application/vnd.denovo.fcselayout-link"
	ApplicationVndDna                                                    MimeType = "application/vnd.dna"
	ApplicationVndDolbyMlp                                               MimeType = "application/vnd.dolby.mlp"
	ApplicationVndDpgraph                                                MimeType = "application/vnd.dpgraph"
	ApplicationVndDreamfactory                                           MimeType = "application/vnd.dreamfactory"
	ApplicationVndDvbAit                                                 MimeType = "application/vnd.dvb.ait"
	ApplicationVndDvbService                                             MimeType = "application/vnd.dvb.service"
	ApplicationVndDynageo                                                MimeType = "application/vnd.dynageo"
	ApplicationVndEcowinChart                                            MimeType = "application/vnd.ecowin.chart"
	ApplicationVndEnliven                                                MimeType = "application/vnd.enliven"
	ApplicationVndEpsonEsf                                               MimeType = "application/vnd.epson.esf"
	ApplicationVndEpsonMsf                                               MimeType = "application/vnd.epson.msf"
	ApplicationVndEpsonQuickanime                                        MimeType = "application/vnd.epson.quickanime"
	ApplicationVndEpsonSalt                                              MimeType = "application/vnd.epson.salt"
	ApplicationVndEpsonSsf                                               MimeType = "application/vnd.epson.ssf"
	ApplicationVndEszigno3Xml                                            MimeType = "application/vnd.eszigno3+xml"
	ApplicationVndEzpixAlbum                                             MimeType = "application/vnd.ezpix-album"
	ApplicationVndEzpixPackage                                           MimeType = "application/vnd.ezpix-package"
	ApplicationVndFdf                                                    MimeType = "application/vnd.fdf"
	ApplicationVndFdsnSeed                                               MimeType = "application/vnd.fdsn.seed"
	ApplicationVndFlographit                                             MimeType = "application/vnd.flographit"
	ApplicationVndFluxtimeClip                                           MimeType = "application/vnd.fluxtime.clip"
	ApplicationVndFramemaker                                             MimeType = "application/vnd.framemaker"
	ApplicationVndFrogansFnc                                             MimeType = "application/vnd.frogans.fnc"
	ApplicationVndFrogansLtf                                             MimeType = "application/vnd.frogans.ltf"
	ApplicationVndFscWeblaunch                                           MimeType = "application/vnd.fsc.weblaunch"
	ApplicationVndFujitsuOasys                                           MimeType = "application/vnd.fujitsu.oasys"
	ApplicationVndFujitsuOasys2                                          MimeType = "application/vnd.fujitsu.oasys2"
	ApplicationVndFujitsuOasys3                                          MimeType = "application/vnd.fujitsu.oasys3"
	ApplicationVndFujitsuOasysgp                                         MimeType = "application/vnd.fujitsu.oasysgp"
	ApplicationVndFujitsuOasysprs                                        MimeType = "application/vnd.fujitsu.oasysprs"
	ApplicationVndFujixeroxDdd                                           MimeType = "application/vnd.fujixerox.ddd"
	ApplicationVndFujixeroxDocuworks                                     MimeType = "application/vnd.fujixerox.docuworks"
	ApplicationVndFujixeroxDocuworksBinder                               MimeType = "application/vnd.fujixerox.docuworks.binder"
	ApplicationVndFuzzysheet                                             MimeType = "application/vnd.fuzzysheet"
	ApplicationVndGenomatixTuxedo                                        MimeType = "application/vnd.genomatix.tuxedo"
	ApplicationVndGeogebraFile                                           MimeType = "application/vnd.geogebra.file"
	ApplicationVndGeogebraTool                                           MimeType = "application/vnd.geogebra.tool"
	ApplicationVndGeometryExplorer                                       MimeType = "application/vnd.geometry-explorer"
	ApplicationVndGeonext                                                MimeType = "application/vnd.geonext"
	ApplicationVndGeoplan                                                MimeType = "application/vnd.geoplan"
	ApplicationVndGeospace                                               MimeType = "application/vnd.geospace"
	ApplicationVndGmx                                                    MimeType = "application/vnd.gmx"
	ApplicationVndGoogleEarthKmlXml                                      MimeType = "application/vnd.google-earth.kml+xml"
	ApplicationVndGoogleEarthKmz                                         MimeType = "application/vnd.google-earth.kmz"
	ApplicationVndGrafeq                                                 MimeType = "application/vnd.grafeq"
	ApplicationVndGrooveAccount                                          MimeType = "application/vnd.groove-account"
	ApplicationVndGrooveHelp                                             MimeType = "application/vnd.groove-help"
	ApplicationVndGrooveIdentityMessage                                  MimeType = "application/vnd.groove-identity-message"
	ApplicationVndGrooveInjector                                         MimeType = "application/vnd.groove-injector"
	ApplicationVndGrooveToolMessage                                      MimeType = "application/vnd.groove-tool-message"
	ApplicationVndGrooveToolTemplate                                     MimeType = "application/vnd.groove-tool-template"
	ApplicationVndGrooveVcard                                            MimeType = "application/vnd.groove-vcard"
	ApplicationVndHalXml                                                 MimeType = "application/vnd.hal+xml"
	ApplicationVndHandheldEntertainmentXml                               MimeType = "application/vnd.handheld-entertainment+xml"
	ApplicationVndHbci                                                   MimeType = "application/vnd.hbci"
	ApplicationVndHheLessonPlayer                                        MimeType = "application/vnd.hhe.lesson-player"
	ApplicationVndHpHpgl                                                 MimeType = "application/vnd.hp-hpgl"
	ApplicationVndHpHpid                                                 MimeType = "application/vnd.hp-hpid"
	ApplicationVndHpHps                                                  MimeType = "application/vnd.hp-hps"
	ApplicationVndHpJlyt                                                 MimeType = "application/vnd.hp-jlyt"
	ApplicationVndHpPcl                                                  MimeType = "application/vnd.hp-pcl"
	ApplicationVndHpPclxl                                                MimeType = "application/vnd.hp-pclxl"
	ApplicationVndHydrostatixSofData                                     MimeType = "application/vnd.hydrostatix.sof-data"
	ApplicationVndHzn3dCrossword                                         MimeType = "application/vnd.hzn-3d-crossword"
	ApplicationVndIbmMinipay                                             MimeType = "application/vnd.ibm.minipay"
	ApplicationVndIbmModcap                                              MimeType = "application/vnd.ibm.modcap"
	ApplicationVndIbmRightsManagement                                    MimeType = "application/vnd.ibm.rights-management"
	ApplicationVndIbmSecureContainer                                     MimeType = "application/vnd.ibm.secure-container"
	ApplicationVndIccprofile                                             MimeType = "application/vnd.iccprofile"
	ApplicationVndIgloader                                               MimeType = "application/vnd.igloader"
	ApplicationVndImmervisionIvp                                         MimeType = "application/vnd.immervision-ivp"
	ApplicationVndImmervisionIvu                                         MimeType = "application/vnd.immervision-ivu"
	ApplicationVndInsorsIgm                                              MimeType = "application/vnd.insors.igm"
	ApplicationVndInterconFormnet                                        MimeType = "application/vnd.intercon.formnet"
	ApplicationVndIntergeo                                               MimeType = "application/vnd.intergeo"
	ApplicationVndIntuQbo                                                MimeType = "application/vnd.intu.qbo"
	ApplicationVndIntuQfx                                                MimeType = "application/vnd.intu.qfx"
	ApplicationVndIpunpluggedRcprofile                                   MimeType = "application/vnd.ipunplugged.rcprofile"
	ApplicationVndIrepositoryPackageXml                                  MimeType = "application/vnd.irepository.package+xml"
	ApplicationVndIsXpr                                                  MimeType = "application/vnd.is-xpr"
	ApplicationVndIsacFcs                                                MimeType = "application/vnd.isac.fcs"
	ApplicationVndJam                                                    MimeType = "application/vnd.jam"
	ApplicationVndJcpJavameMidletRms                                     MimeType = "application/vnd.jcp.javame.midlet-rms"
	ApplicationVndJisp                                                   MimeType = "application/vnd.jisp"
	ApplicationVndJoostJodaArchive                                       MimeType = "application/vnd.joost.joda-archive"
	ApplicationVndKahootz                                                MimeType = "application/vnd.kahootz"
	ApplicationVndKdeKarbon                                              MimeType = "application/vnd.kde.karbon"
	ApplicationVndKdeKchart                                              MimeType = "application/vnd.kde.kchart"
	ApplicationVndKdeKformula                                            MimeType = "application/vnd.kde.kformula"
	ApplicationVndKdeKivio                                               MimeType = "application/vnd.kde.kivio"
	ApplicationVndKdeKontour                                             MimeType = "application/vnd.kde.kontour"
	ApplicationVndKdeKpresenter                                          MimeType = "application/vnd.kde.kpresenter"
	ApplicationVndKdeKspread                                             MimeType = "application/vnd.kde.kspread"
	ApplicationVndKdeKword                                               MimeType = "application/vnd.kde.kword"
	ApplicationVndKenameaapp                                             MimeType = "application/vnd.kenameaapp"
	ApplicationVndKidspiration                                           MimeType = "application/vnd.kidspiration"
	ApplicationVndKinar                                                  MimeType = "application/vnd.kinar"
	ApplicationVndKoan                                                   MimeType = "application/vnd.koan"
	ApplicationVndKodakDescriptor                                        MimeType = "application/vnd.kodak-descriptor"
	ApplicationVndLasLasXml                                              MimeType = "application/vnd.las.las+xml"
	ApplicationVndLlamagraphicsLifeBalanceDesktop                        MimeType = "application/vnd.llamagraphics.life-balance.desktop"
	ApplicationVndLlamagraphicsLifeBalanceExchangeXml                    MimeType = "application/vnd.llamagraphics.life-balance.exchange+xml"
	ApplicationVndLotus123                                               MimeType = "application/vnd.lotus-1-2-3"
	ApplicationVndLotusApproach                                          MimeType = "application/vnd.lotus-approach"
	ApplicationVndLotusFreelance                                         MimeType = "application/vnd.lotus-freelance"
	ApplicationVndLotusNotes                                             MimeType = "application/vnd.lotus-notes"
	ApplicationVndLotusOrganizer                                         MimeType = "application/vnd.lotus-organizer"
	ApplicationVndLotusScreencam                                         MimeType = "application/vnd.lotus-screencam"
	ApplicationVndLotusWordpro                                           MimeType = "application/vnd.lotus-wordpro"
	ApplicationVndMacportsPortpkg                                        MimeType = "application/vnd.macports.portpkg"
	ApplicationVndMcd                                                    MimeType = "application/vnd.mcd"
	ApplicationVndMedcalcdata                                            MimeType = "application/vnd.medcalcdata"
	ApplicationVndMediastationCdkey                                      MimeType = "application/vnd.mediastation.cdkey"
	ApplicationVndMfer                                                   MimeType = "application/vnd.mfer"
	ApplicationVndMfmp                                                   MimeType = "application/vnd.mfmp"
	ApplicationVndMicrografxFlo                                          MimeType = "application/vnd.micrografx.flo"
	ApplicationVndMicrografxIgx                                          MimeType = "application/vnd.micrografx.igx"
	ApplicationVndMif                                                    MimeType = "application/vnd.mif"
	ApplicationVndMobiusDaf                                              MimeType = "application/vnd.mobius.daf"
	ApplicationVndMobiusDis                                              MimeType = "application/vnd.mobius.dis"
	ApplicationVndMobiusMbk                                              MimeType = "application/vnd.mobius.mbk"
	ApplicationVndMobiusMqy                                              MimeType = "application/vnd.mobius.mqy"
	ApplicationVndMobiusMsl                                              MimeType = "application/vnd.mobius.msl"
	ApplicationVndMobiusPlc                                              MimeType = "application/vnd.mobius.plc"
	ApplicationVndMobiusTxf                                              MimeType = "application/vnd.mobius.txf"
	ApplicationVndMophunApplication                                      MimeType = "application/vnd.mophun.application"
	ApplicationVndMophunCertificate                                      MimeType = "application/vnd.mophun.certificate"
	ApplicationVndMozillaXulXml                                          MimeType = "application/vnd.mozilla.xul+xml"
	ApplicationVndMsArtgalry                                             MimeType = "application/vnd.ms-artgalry"
	ApplicationVndMsCabCompressed                                        MimeType = "application/vnd.ms-cab-compressed"
	ApplicationVndMsExcel                                                MimeType = "application/vnd.ms-excel"
	ApplicationVndMsExcelAddinMacroenabled12                             MimeType = "application/vnd.ms-excel.addin.macroenabled.12"
	ApplicationVndMsExcelSheetBinaryMacroenabled12                       MimeType = "application/vnd.ms-excel.sheet.binary.macroenabled.12"
	ApplicationVndMsExcelSheetMacroenabled12                             MimeType = "application/vnd.ms-excel.sheet.macroenabled.12"
	ApplicationVndMsExcelTemplateMacroenabled12                          MimeType = "application/vnd.ms-excel.template.macroenabled.12"
	ApplicationVndMsFontobject                                           MimeType = "application/vnd.ms-fontobject"
	ApplicationVndMsHtmlhelp                                             MimeType = "application/vnd.ms-htmlhelp"
	ApplicationVndMsIms                                                  MimeType = "application/vnd.ms-ims"
	ApplicationVndMsLrm                                                  MimeType = "application/vnd.ms-lrm"
	ApplicationVndMsOfficetheme                                          MimeType = "application/vnd.ms-officetheme"
	ApplicationVndMsPkiSeccat                                            MimeType = "application/vnd.ms-pki.seccat"
	ApplicationVndMsPkiStl                                               MimeType = "application/vnd.ms-pki.stl"
	ApplicationVndMsPowerpoint                                           MimeType = "application/vnd.ms-powerpoint"
	ApplicationVndMsPowerpointAddinMacroenabled12                        MimeType = "application/vnd.ms-powerpoint.addin.macroenabled.12"
	ApplicationVndMsPowerpointPresentationMacroenabled12                 MimeType = "application/vnd.ms-powerpoint.presentation.macroenabled.12"
	ApplicationVndMsPowerpointSlideMacroenabled12                        MimeType = "application/vnd.ms-powerpoint.slide.macroenabled.12"
	ApplicationVndMsPowerpointSlideshowMacroenabled12                    MimeType = "application/vnd.ms-powerpoint.slideshow.macroenabled.12"
	ApplicationVndMsPowerpointTemplateMacroenabled12                     MimeType = "application/vnd.ms-powerpoint.template.macroenabled.12"
	ApplicationVndMsProject                                              MimeType = "application/vnd.ms-project"
	ApplicationVndMsWordDocumentMacroenabled12                           MimeType = "application/vnd.ms-word.document.macroenabled.12"
	ApplicationVndMsWordTemplateMacroenabled12                           MimeType = "application/vnd.ms-word.template.macroenabled.12"
	ApplicationVndMsWorks                                                MimeType = "application/vnd.ms-works"
	ApplicationVndMsWpl                                                  MimeType = "application/vnd.ms-wpl"
	ApplicationVndMsXpsdocument                                          MimeType = "application/vnd.ms-xpsdocument"
	ApplicationVndMseq                                                   MimeType = "application/vnd.mseq"
	ApplicationVndMusician                                               MimeType = "application/vnd.musician"
	ApplicationVndMuveeStyle                                             MimeType = "application/vnd.muvee.style"
	ApplicationVndNeurolanguageNlu                                       MimeType = "application/vnd.neurolanguage.nlu"
	ApplicationVndNoblenetDirectory                                      MimeType = "application/vnd.noblenet-directory"
	ApplicationVndNoblenetSealer                                         MimeType = "application/vnd.noblenet-sealer"
	ApplicationVndNoblenetWeb                                            MimeType = "application/vnd.noblenet-web"
	ApplicationVndNokiaNGageData                                         MimeType = "application/vnd.nokia.n-gage.data"
	ApplicationVndNokiaNGageSymbianInstall                               MimeType = "application/vnd.nokia.n-gage.symbian.install"
	ApplicationVndNokiaRadioPreset                                       MimeType = "application/vnd.nokia.radio-preset"
	ApplicationVndNokiaRadioPresets                                      MimeType = "application/vnd.nokia.radio-presets"
	ApplicationVndNovadigmEdm                                            MimeType = "application/vnd.novadigm.edm"
	ApplicationVndNovadigmEdx                                            MimeType = "application/vnd.novadigm.edx"
	ApplicationVndNovadigmExt                                            MimeType = "application/vnd.novadigm.ext"
	ApplicationVndOasisOpendocumentChart                                 MimeType = "application/vnd.oasis.opendocument.chart"
	ApplicationVndOasisOpendocumentChartTemplate                         MimeType = "application/vnd.oasis.opendocument.chart-template"
	ApplicationVndOasisOpendocumentDatabase                              MimeType = "application/vnd.oasis.opendocument.database"
	ApplicationVndOasisOpendocumentFormula                               MimeType = "application/vnd.oasis.opendocument.formula"
	ApplicationVndOasisOpendocumentFormulaTemplate                       MimeType = "application/vnd.oasis.opendocument.formula-template"
	ApplicationVndOasisOpendocumentGraphics                              MimeType = "application/vnd.oasis.opendocument.graphics"
	ApplicationVndOasisOpendocumentGraphicsTemplate                      MimeType = "application/vnd.oasis.opendocument.graphics-template"
	ApplicationVndOasisOpendocumentImage                                 MimeType = "application/vnd.oasis.opendocument.image"
	ApplicationVndOasisOpendocumentImageTemplate                         MimeType = "application/vnd.oasis.opendocument.image-template"
	ApplicationVndOasisOpendocumentPresentation                          MimeType = "application/vnd.oasis.opendocument.presentation"
	ApplicationVndOasisOpendocumentPresentationTemplate                  MimeType = "application/vnd.oasis.opendocument.presentation-template"
	ApplicationVndOasisOpendocumentSpreadsheet                           MimeType = "application/vnd.oasis.opendocument.spreadsheet"
	ApplicationVndOasisOpendocumentSpreadsheetTemplate                   MimeType = "application/vnd.oasis.opendocument.spreadsheet-template"
	ApplicationVndOasisOpendocumentText                                  MimeType = "application/vnd.oasis.opendocument.text"
	ApplicationVndOasisOpendocumentTextMaster                            MimeType = "application/vnd.oasis.opendocument.text-master"
	ApplicationVndOasisOpendocumentTextTemplate                          MimeType = "application/vnd.oasis.opendocument.text-template"
	ApplicationVndOasisOpendocumentTextWeb                               MimeType = "application/vnd.oasis.opendocument.text-web"
	ApplicationVndOlpcSugar                                              MimeType = "application/vnd.olpc-sugar"
	ApplicationVndOmaDd2Xml                                              MimeType = "application/vnd.oma.dd2+xml"
	ApplicationVndOpenofficeorgExtension                                 MimeType = "application/vnd.openofficeorg.extension"
	ApplicationVndOpenxmlformatsOfficedocumentPresentationmlPresentation MimeType = "application/vnd.openxmlformats-officedocument.presentationml.presentation"
	ApplicationVndOpenxmlformatsOfficedocumentPresentationmlSlide        MimeType = "application/vnd.openxmlformats-officedocument.presentationml.slide"
	ApplicationVndOpenxmlformatsOfficedocumentPresentationmlSlideshow    MimeType = "application/vnd.openxmlformats-officedocument.presentationml.slideshow"
	ApplicationVndOpenxmlformatsOfficedocumentPresentationmlTemplate     MimeType = "application/vnd.openxmlformats-officedocument.presentationml.template"
	ApplicationVndOpenxmlformatsOfficedocumentSpreadsheetmlSheet         MimeType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
	ApplicationVndOpenxmlformatsOfficedocumentSpreadsheetmlTemplate      MimeType = "application/vnd.openxmlformats-officedocument.spreadsheetml.template"
	ApplicationVndOpenxmlformatsOfficedocumentWordprocessingmlDocument   MimeType = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
	ApplicationVndOpenxmlformatsOfficedocumentWordprocessingmlTemplate   MimeType = "application/vnd.openxmlformats-officedocument.wordprocessingml.template"
	ApplicationVndOsgeoMapguidePackage                                   MimeType = "application/vnd.osgeo.mapguide.package"
	ApplicationVndOsgiDp                                                 MimeType = "application/vnd.osgi.dp"
	ApplicationVndPalm                                                   MimeType = "application/vnd.palm"
	ApplicationVndPawaafile                                              MimeType = "application/vnd.pawaafile"
	ApplicationVndPgFormat                                               MimeType = "application/vnd.pg.format"
	ApplicationVndPgOsasli                                               MimeType = "application/vnd.pg.osasli"
	ApplicationVndPicsel                                                 MimeType = "application/vnd.picsel"
	ApplicationVndPmiWidget                                              MimeType = "application/vnd.pmi.widget"
	ApplicationVndPocketlearn                                            MimeType = "application/vnd.pocketlearn"
	ApplicationVndPowerbuilder6                                          MimeType = "application/vnd.powerbuilder6"
	ApplicationVndPreviewsystemsBox                                      MimeType = "application/vnd.previewsystems.box"
	ApplicationVndProteusMagazine                                        MimeType = "application/vnd.proteus.magazine"
	ApplicationVndPublishareDeltaTree                                    MimeType = "application/vnd.publishare-delta-tree"
	ApplicationVndPviPtid1                                               MimeType = "application/vnd.pvi.ptid1"
	ApplicationVndQuarkQuarkxpress                                       MimeType = "application/vnd.quark.quarkxpress"
	ApplicationVndRar                                                    MimeType = "application/vnd.rar"
	ApplicationVndRealvncBed                                             MimeType = "application/vnd.realvnc.bed"
	ApplicationVndRecordareMusicxml                                      MimeType = "application/vnd.recordare.musicxml"
	ApplicationVndRecordareMusicxmlXml                                   MimeType = "application/vnd.recordare.musicxml+xml"
	ApplicationVndRigCryptonote                                          MimeType = "application/vnd.rig.cryptonote"
	ApplicationVndRimCod                                                 MimeType = "application/vnd.rim.cod"
	ApplicationVndRnRealmedia                                            MimeType = "application/vnd.rn-realmedia"
	ApplicationVndRoute66Link66Xml                                       MimeType = "application/vnd.route66.link66+xml"
	ApplicationVndSailingtrackerTrack                                    MimeType = "application/vnd.sailingtracker.track"
	ApplicationVndSeemail                                                MimeType = "application/vnd.seemail"
	ApplicationVndSema                                                   MimeType = "application/vnd.sema"
	ApplicationVndSemd                                                   MimeType = "application/vnd.semd"
	ApplicationVndSemf                                                   MimeType = "application/vnd.semf"
	ApplicationVndShanaInformedFormdata                                  MimeType = "application/vnd.shana.informed.formdata"
	ApplicationVndShanaInformedFormtemplate                              MimeType = "application/vnd.shana.informed.formtemplate"
	ApplicationVndShanaInformedInterchange                               MimeType = "application/vnd.shana.informed.interchange"
	ApplicationVndShanaInformedPackage                                   MimeType = "application/vnd.shana.informed.package"
	ApplicationVndSimtechMindmapper                                      MimeType = "application/vnd.simtech-mindmapper"
	ApplicationVndSmaf                                                   MimeType = "application/vnd.smaf"
	ApplicationVndSmartTeacher                                           MimeType = "application/vnd.smart.teacher"
	ApplicationVndSolentSdkmXml                                          MimeType = "application/vnd.solent.sdkm+xml"
	ApplicationVndSpotfireDxp                                            MimeType = "application/vnd.spotfire.dxp"
	ApplicationVndSpotfireSfs                                            MimeType = "application/vnd.spotfire.sfs"
	ApplicationVndStardivisionCalc                                       MimeType = "application/vnd.stardivision.calc"
	ApplicationVndStardivisionDraw                                       MimeType = "application/vnd.stardivision.draw"
	ApplicationVndStardivisionImpress                                    MimeType = "application/vnd.stardivision.impress"
	ApplicationVndStardivisionMath                                       MimeType = "application/vnd.stardivision.math"
	ApplicationVndStardivisionWriter                                     MimeType = "application/vnd.stardivision.writer"
	ApplicationVndStardivisionWriterGlobal                               MimeType = "application/vnd.stardivision.writer-global"
	ApplicationVndStepmaniaStepchart                                     MimeType = "application/vnd.stepmania.stepchart"
	ApplicationVndSunXmlCalc                                             MimeType = "application/vnd.sun.xml.calc"
	ApplicationVndSunXmlCalcTemplate                                     MimeType = "application/vnd.sun.xml.calc.template"
	ApplicationVndSunXmlDraw                                             MimeType = "application/vnd.sun.xml.draw"
	ApplicationVndSunXmlDrawTemplate                                     MimeType = "application/vnd.sun.xml.draw.template"
	ApplicationVndSunXmlImpress                                          MimeType = "application/vnd.sun.xml.impress"
	ApplicationVndSunXmlImpressTemplate                                  MimeType = "application/vnd.sun.xml.impress.template"
	ApplicationVndSunXmlMath                                             MimeType = "application/vnd.sun.xml.math"
	ApplicationVndSunXmlWriter                                           MimeType = "application/vnd.sun.xml.writer"
	ApplicationVndSunXmlWriterGlobal                                     MimeType = "application/vnd.sun.xml.writer.global"
	ApplicationVndSunXmlWriterTemplate                                   MimeType = "application/vnd.sun.xml.writer.template"
	ApplicationVndSusCalendar                                            MimeType = "application/vnd.sus-calendar"
	ApplicationVndSvd                                                    MimeType = "application/vnd.svd"
	ApplicationVndSymbianInstall                                         MimeType = "application/vnd.symbian.install"
	ApplicationVndSyncmlDmWbxml                                          MimeType = "application/vnd.syncml.dm+wbxml"
	ApplicationVndSyncmlDmXml                                            MimeType = "application/vnd.syncml.dm+xml"
	ApplicationVndSyncmlXml                                              MimeType = "application/vnd.syncml+xml"
	ApplicationVndTaoIntentModuleArchive                                 MimeType = "application/vnd.tao.intent-module-archive"
	ApplicationVndTmobileLivetv                                          MimeType = "application/vnd.tmobile-livetv"
	ApplicationVndTridTpt                                                MimeType = "application/vnd.trid.tpt"
	ApplicationVndTriscapeMxs                                            MimeType = "application/vnd.triscape.mxs"
	ApplicationVndTrueapp                                                MimeType = "application/vnd.trueapp"
	ApplicationVndUfdl                                                   MimeType = "application/vnd.ufdl"
	ApplicationVndUiqTheme                                               MimeType = "application/vnd.uiq.theme"
	ApplicationVndUmajin                                                 MimeType = "application/vnd.umajin"
	ApplicationVndUnity                                                  MimeType = "application/vnd.unity"
	ApplicationVndUomlXml                                                MimeType = "application/vnd.uoml+xml"
	ApplicationVndVcx                                                    MimeType = "application/vnd.vcx"
	ApplicationVndVisio                                                  MimeType = "application/vnd.visio"
	ApplicationVndVisio2013                                              MimeType = "application/vnd.visio2013"
	ApplicationVndVisionary                                              MimeType = "application/vnd.visionary"
	ApplicationVndVsf                                                    MimeType = "application/vnd.vsf"
	ApplicationVndWapWbxml                                               MimeType = "application/vnd.wap.wbxml"
	ApplicationVndWapWmlc                                                MimeType = "application/vnd.wap.wmlc"
	ApplicationVndWapWmlscriptc                                          MimeType = "application/vnd.wap.wmlscriptc"
	ApplicationVndWebturbo                                               MimeType = "application/vnd.webturbo"
	ApplicationVndWolframPlayer                                          MimeType = "application/vnd.wolfram.player"
	ApplicationVndWordperfect                                            MimeType = "application/vnd.wordperfect"
	ApplicationVndWqd                                                    MimeType = "application/vnd.wqd"
	ApplicationVndWtStf                                                  MimeType = "application/vnd.wt.stf"
	ApplicationVndXara                                                   MimeType = "application/vnd.xara"
	ApplicationVndXfdl                                                   MimeType = "application/vnd.xfdl"
	ApplicationVndYamahaHvDic                                            MimeType = "application/vnd.yamaha.hv-dic"
	ApplicationVndYamahaHvScript                                         MimeType = "application/vnd.yamaha.hv-script"
	ApplicationVndYamahaHvVoice                                          MimeType = "application/vnd.yamaha.hv-voice"
	ApplicationVndYamahaOpenscoreformat                                  MimeType = "application/vnd.yamaha.openscoreformat"
	ApplicationVndYamahaOpenscoreformatOsfpvgXml                         MimeType = "application/vnd.yamaha.openscoreformat.osfpvg+xml"
	ApplicationVndYamahaSmafAudio                                        MimeType = "application/vnd.yamaha.smaf-audio"
	ApplicationVndYamahaSmafPhrase                                       MimeType = "application/vnd.yamaha.smaf-phrase"
	ApplicationVndYellowriverCustomMenu                                  MimeType = "application/vnd.yellowriver-custom-menu"
	ApplicationVndZul                                                    MimeType = "application/vnd.zul"
	ApplicationVndZzazzDeckXml                                           MimeType = "application/vnd.zzazz.deck+xml"
	ApplicationVoicexmlXml                                               MimeType = "application/voicexml+xml"
	ApplicationWidget                                                    MimeType = "application/widget"
	ApplicationWinhlp                                                    MimeType = "application/winhlp"
	ApplicationWsdlXml                                                   MimeType = "application/wsdl+xml"
	ApplicationWspolicyXml                                               MimeType = "application/wspolicy+xml"
	ApplicationX7zCompressed                                             MimeType = "application/x-7z-compressed"
	ApplicationXAbiword                                                  MimeType = "application/x-abiword"
	ApplicationXAceCompressed                                            MimeType = "application/x-ace-compressed"
	ApplicationXAppleDiskimage                                           MimeType = "application/x-apple-diskimage"
	ApplicationXAuthorwareBin                                            MimeType = "application/x-authorware-bin"
	ApplicationXAuthorwareMap                                            MimeType = "application/x-authorware-map"
	ApplicationXAuthorwareSeg                                            MimeType = "application/x-authorware-seg"
	ApplicationXBcpio                                                    MimeType = "application/x-bcpio"
	ApplicationXBittorrent                                               MimeType = "application/x-bittorrent"
	ApplicationXBzip                                                     MimeType = "application/x-bzip"
	ApplicationXBzip2                                                    MimeType = "application/x-bzip2"
	ApplicationXCdf                                                      MimeType = "application/x-cdf"
	ApplicationXCdlink                                                   MimeType = "application/x-cdlink"
	ApplicationXChat                                                     MimeType = "application/x-chat"
	ApplicationXChessPgn                                                 MimeType = "application/x-chess-pgn"
	ApplicationXCpio                                                     MimeType = "application/x-cpio"
	ApplicationXCsh                                                      MimeType = "application/x-csh"
	ApplicationXDebianPackage                                            MimeType = "application/x-debian-package"
	ApplicationXDirector                                                 MimeType = "application/x-director"
	ApplicationXDoom                                                     MimeType = "application/x-doom"
	ApplicationXDtbncxXml                                                MimeType = "application/x-dtbncx+xml"
	ApplicationXDtbookXml                                                MimeType = "application/x-dtbook+xml"
	ApplicationXDtbresourceXml                                           MimeType = "application/x-dtbresource+xml"
	ApplicationXDvi                                                      MimeType = "application/x-dvi"
	ApplicationXFontBdf                                                  MimeType = "application/x-font-bdf"
	ApplicationXFontGhostscript                                          MimeType = "application/x-font-ghostscript"
	ApplicationXFontLinuxPsf                                             MimeType = "application/x-font-linux-psf"
	ApplicationXFontOtf                                                  MimeType = "application/x-font-otf"
	ApplicationXFontPcf                                                  MimeType = "application/x-font-pcf"
	ApplicationXFontSnf                                                  MimeType = "application/x-font-snf"
	ApplicationXFontTtf                                                  MimeType = "application/x-font-ttf"
	ApplicationXFontType1                                                MimeType = "application/x-font-type1"
	ApplicationXFontWoff                                                 MimeType = "application/x-font-woff"
	ApplicationXFreearc                                                  MimeType = "application/x-freearc"
	ApplicationXFuturesplash                                             MimeType = "application/x-futuresplash"
	ApplicationXGnumeric                                                 MimeType = "application/x-gnumeric"
	ApplicationXGtar                                                     MimeType = "application/x-gtar"
	ApplicationXHdf                                                      MimeType = "application/x-hdf"
	ApplicationXHttpdPhp                                                 MimeType = "application/x-httpd-php"
	ApplicationXJavaJnlpFile                                             MimeType = "application/x-java-jnlp-file"
	ApplicationXLatex                                                    MimeType = "application/x-latex"
	ApplicationXMobipocketEbook                                          MimeType = "application/x-mobipocket-ebook"
	ApplicationXMsApplication                                            MimeType = "application/x-ms-application"
	ApplicationXMsWmd                                                    MimeType = "application/x-ms-wmd"
	ApplicationXMsWmz                                                    MimeType = "application/x-ms-wmz"
	ApplicationXMsXbap                                                   MimeType = "application/x-ms-xbap"
	ApplicationXMsaccess                                                 MimeType = "application/x-msaccess"
	ApplicationXMsbinder                                                 MimeType = "application/x-msbinder"
	ApplicationXMscardfile                                               MimeType = "application/x-mscardfile"
	ApplicationXMsclip                                                   MimeType = "application/x-msclip"
	ApplicationXMsdownload                                               MimeType = "application/x-msdownload"
	ApplicationXMsmediaview                                              MimeType = "application/x-msmediaview"
	ApplicationXMsmetafile                                               MimeType = "application/x-msmetafile"
	ApplicationXMsmoney                                                  MimeType = "application/x-msmoney"
	ApplicationXMspublisher                                              MimeType = "application/x-mspublisher"
	ApplicationXMsschedule                                               MimeType = "application/x-msschedule"
	ApplicationXMsterminal                                               MimeType = "application/x-msterminal"
	ApplicationXMswrite                                                  MimeType = "application/x-mswrite"
	ApplicationXNetcdf                                                   MimeType = "application/x-netcdf"
	ApplicationXPkcs12                                                   MimeType = "application/x-pkcs12"
	ApplicationXPkcs7Certificates                                        MimeType = "application/x-pkcs7-certificates"
	ApplicationXPkcs7Certreqresp                                         MimeType = "application/x-pkcs7-certreqresp"
	ApplicationXRarCompressed                                            MimeType = "application/x-rar-compressed"
	ApplicationXSh                                                       MimeType = "application/x-sh"
	ApplicationXShar                                                     MimeType = "application/x-shar"
	ApplicationXShockwaveFlash                                           MimeType = "application/x-shockwave-flash"
	ApplicationXSilverlightApp                                           MimeType = "application/x-silverlight-app"
	ApplicationXStuffit                                                  MimeType = "application/x-stuffit"
	ApplicationXStuffitx                                                 MimeType = "application/x-stuffitx"
	ApplicationXSv4cpio                                                  MimeType = "application/x-sv4cpio"
	ApplicationXSv4crc                                                   MimeType = "application/x-sv4crc"
	ApplicationXTar                                                      MimeType = "application/x-tar"
	ApplicationXTcl                                                      MimeType = "application/x-tcl"
	ApplicationXTex                                                      MimeType = "application/x-tex"
	ApplicationXTexTfm                                                   MimeType = "application/x-tex-tfm"
	ApplicationXTexinfo                                                  MimeType = "application/x-texinfo"
	ApplicationXUstar                                                    MimeType = "application/x-ustar"
	ApplicationXWaisSource                                               MimeType = "application/x-wais-source"
	ApplicationXX509CaCert                                               MimeType = "application/x-x509-ca-cert"
	ApplicationXXfig                                                     MimeType = "application/x-xfig"
	ApplicationXXpinstall                                                MimeType = "application/x-xpinstall"
	ApplicationXYaml                                                     MimeType = "application/x-yaml"
	ApplicationXcapDiffXml                                               MimeType = "application/xcap-diff+xml"
	ApplicationXencXml                                                   MimeType = "application/xenc+xml"
	ApplicationXhtmlXml                                                  MimeType = "application/xhtml+xml"
	ApplicationXml                                                       MimeType = "application/xml"
	ApplicationXmlDtd                                                    MimeType = "application/xml-dtd"
	ApplicationXopXml                                                    MimeType = "application/xop+xml"
	ApplicationXsltXml                                                   MimeType = "application/xslt+xml"
	ApplicationXspfXml                                                   MimeType = "application/xspf+xml"
	ApplicationXvXml                                                     MimeType = "application/xv+xml"
	ApplicationYang                                                      MimeType = "application/yang"
	ApplicationYinXml                                                    MimeType = "application/yin+xml"
	ApplicationZip                                                       MimeType = "application/zip"
	Audio3gpp                                                            MimeType = "audio/3gpp"
	Audio3gpp2                                                           MimeType = "audio/3gpp2"
	AudioAdpcm                                                           MimeType = "audio/adpcm"
	AudioBasic                                                           MimeType = "audio/basic"
	AudioMidi                                                            MimeType = "audio/midi"
	AudioMp4                                                             MimeType = "audio/mp4"
	AudioMpeg                                                            MimeType = "audio/mpeg"
	AudioOgg                                                             MimeType = "audio/ogg"
	AudioOpus                                                            MimeType = "audio/opus"
	AudioVndDeceAudio                                                    MimeType = "audio/vnd.dece.audio"
	AudioVndDigitalWinds                                                 MimeType = "audio/vnd.digital-winds"
	AudioVndDra                                                          MimeType = "audio/vnd.dra"
	AudioVndDts                                                          MimeType = "audio/vnd.dts"
	AudioVndDtsHd                                                        MimeType = "audio/vnd.dts.hd"
	AudioVndLucentVoice                                                  MimeType = "audio/vnd.lucent.voice"
	AudioVndMsPlayreadyMediaPya                                          MimeType = "audio/vnd.ms-playready.media.pya"
	AudioVndNueraEcelp4800                                               MimeType = "audio/vnd.nuera.ecelp4800"
	AudioVndNueraEcelp7470                                               MimeType = "audio/vnd.nuera.ecelp7470"
	AudioVndNueraEcelp9600                                               MimeType = "audio/vnd.nuera.ecelp9600"
	AudioVndRip                                                          MimeType = "audio/vnd.rip"
	AudioWav                                                             MimeType = "audio/wav"
	AudioWebm                                                            MimeType = "audio/webm"
	AudioXAac                                                            MimeType = "audio/x-aac"
	AudioXAiff                                                           MimeType = "audio/x-aiff"
	AudioXMidi                                                           MimeType = "audio/x-midi"
	AudioXMpegurl                                                        MimeType = "audio/x-mpegurl"
	AudioXMsWax                                                          MimeType = "audio/x-ms-wax"
	AudioXMsWma                                                          MimeType = "audio/x-ms-wma"
	AudioXPnRealaudio                                                    MimeType = "audio/x-pn-realaudio"
	AudioXPnRealaudioPlugin                                              MimeType = "audio/x-pn-realaudio-plugin"
	AudioXWav                                                            MimeType = "audio/x-wav"
	ChemicalXCdx                                                         MimeType = "chemical/x-cdx"
	ChemicalXCif                                                         MimeType = "chemical/x-cif"
	ChemicalXCmdf                                                        MimeType = "chemical/x-cmdf"
	ChemicalXCml                                                         MimeType = "chemical/x-cml"
	ChemicalXCsml                                                        MimeType = "chemical/x-csml"
	ChemicalXXyz                                                         MimeType = "chemical/x-xyz"
	FontOtf                                                              MimeType = "font/otf"
	FontTtf                                                              MimeType = "font/ttf"
	FontWoff                                                             MimeType = "font/woff"
	FontWoff2                                                            MimeType = "font/woff2"
	ImageBmp                                                             MimeType = "image/bmp"
	ImageCgm                                                             MimeType = "image/cgm"
	ImageG3fax                                                           MimeType = "image/g3fax"
	ImageGif                                                             MimeType = "image/gif"
	ImageIef                                                             MimeType = "image/ief"
	ImageJpeg                                                            MimeType = "image/jpeg"
	ImageKtx                                                             MimeType = "image/ktx"
	ImagePjpeg                                                           MimeType = "image/pjpeg"
	ImagePng                                                             MimeType = "image/png"
	ImagePrsBtif                                                         MimeType = "image/prs.btif"
	ImageSvgXml                                                          MimeType = "image/svg+xml"
	ImageTiff                                                            MimeType = "image/tiff"
	ImageVndAdobePhotoshop                                               MimeType = "image/vnd.adobe.photoshop"
	ImageVndDeceGraphic                                                  MimeType = "image/vnd.dece.graphic"
	ImageVndDjvu                                                         MimeType = "image/vnd.djvu"
	ImageVndDvbSubtitle                                                  MimeType = "image/vnd.dvb.subtitle"
	ImageVndDwg                                                          MimeType = "image/vnd.dwg"
	ImageVndDxf                                                          MimeType = "image/vnd.dxf"
	ImageVndFastbidsheet                                                 MimeType = "image/vnd.fastbidsheet"
	ImageVndFpx                                                          MimeType = "image/vnd.fpx"
	ImageVndFst                                                          MimeType = "image/vnd.fst"
	ImageVndFujixeroxEdmicsMmr                                           MimeType = "image/vnd.fujixerox.edmics-mmr"
	ImageVndFujixeroxEdmicsRlc                                           MimeType = "image/vnd.fujixerox.edmics-rlc"
	ImageVndMicrosoftIcon                                                MimeType = "image/vnd.microsoft.icon"
	ImageVndMsModi                                                       MimeType = "image/vnd.ms-modi"
	ImageVndNetFpx                                                       MimeType = "image/vnd.net-fpx"
	ImageVndWapWbmp                                                      MimeType = "image/vnd.wap.wbmp"
	ImageVndXiff                                                         MimeType = "image/vnd.xiff"
	ImageWebp                                                            MimeType = "image/webp"
	ImageXCitrixJpeg                                                     MimeType = "image/x-citrix-jpeg"
	ImageXCitrixPng                                                      MimeType = "image/x-citrix-png"
	ImageXCmuRaster                                                      MimeType = "image/x-cmu-raster"
	ImageXCmx                                                            MimeType = "image/x-cmx"
	ImageXFreehand                                                       MimeType = "image/x-freehand"
	ImageXIcon                                                           MimeType = "image/x-icon"
	ImageXPcx                                                            MimeType = "image/x-pcx"
	ImageXPict                                                           MimeType = "image/x-pict"
	ImageXPng                                                            MimeType = "image/x-png"
	ImageXPortableAnymap                                                 MimeType = "image/x-portable-anymap"
	ImageXPortableBitmap                                                 MimeType = "image/x-portable-bitmap"
	ImageXPortableGraymap                                                MimeType = "image/x-portable-graymap"
	ImageXPortablePixmap                                                 MimeType = "image/x-portable-pixmap"
	ImageXRgb                                                            MimeType = "image/x-rgb"
	ImageXXbitmap                                                        MimeType = "image/x-xbitmap"
	ImageXXpixmap                                                        MimeType = "image/x-xpixmap"
	ImageXXwindowdump                                                    MimeType = "image/x-xwindowdump"
	Java                                                                 MimeType = "java"
	MessageRfc822                                                        MimeType = "message/rfc822"
	ModelIges                                                            MimeType = "model/iges"
	ModelMesh                                                            MimeType = "model/mesh"
	ModelVndColladaXml                                                   MimeType = "model/vnd.collada+xml"
	ModelVndDwf                                                          MimeType = "model/vnd.dwf"
	ModelVndGdl                                                          MimeType = "model/vnd.gdl"
	ModelVndGtw                                                          MimeType = "model/vnd.gtw"
	ModelVndMts                                                          MimeType = "model/vnd.mts"
	ModelVndVtu                                                          MimeType = "model/vnd.vtu"
	ModelVrml                                                            MimeType = "model/vrml"
	TextCalendar                                                         MimeType = "text/calendar"
	TextCss                                                              MimeType = "text/css"
	TextCsv                                                              MimeType = "text/csv"
	TextHtml                                                             MimeType = "text/html"
	TextJavascript                                                       MimeType = "text/javascript"
	TextN3                                                               MimeType = "text/n3"
	TextPlain                                                            MimeType = "text/plain"
	TextPlainBas                                                         MimeType = "text/plain-bas"
	TextPrsLinesTag                                                      MimeType = "text/prs.lines.tag"
	TextRichtext                                                         MimeType = "text/richtext"
	TextSgml                                                             MimeType = "text/sgml"
	TextTabSeparatedValues                                               MimeType = "text/tab-separated-values"
	TextTroff                                                            MimeType = "text/troff"
	TextTurtle                                                           MimeType = "text/turtle"
	TextUriList                                                          MimeType = "text/uri-list"
	TextVndCurl                                                          MimeType = "text/vnd.curl"
	TextVndCurlDcurl                                                     MimeType = "text/vnd.curl.dcurl"
	TextVndCurlMcurl                                                     MimeType = "text/vnd.curl.mcurl"
	TextVndCurlScurl                                                     MimeType = "text/vnd.curl.scurl"
	TextVndFly                                                           MimeType = "text/vnd.fly"
	TextVndFmiFlexstor                                                   MimeType = "text/vnd.fmi.flexstor"
	TextVndGraphviz                                                      MimeType = "text/vnd.graphviz"
	TextVndIn3d3dml                                                      MimeType = "text/vnd.in3d.3dml"
	TextVndIn3dSpot                                                      MimeType = "text/vnd.in3d.spot"
	TextVndSunJ2meAppDescriptor                                          MimeType = "text/vnd.sun.j2me.app-descriptor"
	TextVndWapWml                                                        MimeType = "text/vnd.wap.wml"
	TextVndWapWmlscript                                                  MimeType = "text/vnd.wap.wmlscript"
	TextXAsm                                                             MimeType = "text/x-asm"
	TextXC                                                               MimeType = "text/x-c"
	TextXFortran                                                         MimeType = "text/x-fortran"
	TextXJavaSource                                                      MimeType = "text/x-java-source"
	TextXPascal                                                          MimeType = "text/x-pascal"
	TextXSetext                                                          MimeType = "text/x-setext"
	TextXUuencode                                                        MimeType = "text/x-uuencode"
	TextXVcalendar                                                       MimeType = "text/x-vcalendar"
	TextXVcard                                                           MimeType = "text/x-vcard"
	TextXYaml                                                            MimeType = "text/x-yaml"
	TextXml                                                              MimeType = "text/xml"
	TextYaml                                                             MimeType = "text/yaml"
	Unkown                                                               MimeType = "unkown"
	Video3gpp                                                            MimeType = "video/3gpp"
	Video3gpp2                                                           MimeType = "video/3gpp2"
	VideoH261                                                            MimeType = "video/h261"
	VideoH263                                                            MimeType = "video/h263"
	VideoH264                                                            MimeType = "video/h264"
	VideoJpeg                                                            MimeType = "video/jpeg"
	VideoJpm                                                             MimeType = "video/jpm"
	VideoMj2                                                             MimeType = "video/mj2"
	VideoMp2t                                                            MimeType = "video/mp2t"
	VideoMp4                                                             MimeType = "video/mp4"
	VideoMpeg                                                            MimeType = "video/mpeg"
	VideoOgg                                                             MimeType = "video/ogg"
	VideoQuicktime                                                       MimeType = "video/quicktime"
	VideoVndDeceHd                                                       MimeType = "video/vnd.dece.hd"
	VideoVndDeceMobile                                                   MimeType = "video/vnd.dece.mobile"
	VideoVndDecePd                                                       MimeType = "video/vnd.dece.pd"
	VideoVndDeceSd                                                       MimeType = "video/vnd.dece.sd"
	VideoVndDeceVideo                                                    MimeType = "video/vnd.dece.video"
	VideoVndFvt                                                          MimeType = "video/vnd.fvt"
	VideoVndMpegurl                                                      MimeType = "video/vnd.mpegurl"
	VideoVndMsPlayreadyMediaPyv                                          MimeType = "video/vnd.ms-playready.media.pyv"
	VideoVndUvvuMp4                                                      MimeType = "video/vnd.uvvu.mp4"
	VideoVndVivo                                                         MimeType = "video/vnd.vivo"
	VideoWebm                                                            MimeType = "video/webm"
	VideoXF4v                                                            MimeType = "video/x-f4v"
	VideoXFli                                                            MimeType = "video/x-fli"
	VideoXFlv                                                            MimeType = "video/x-flv"
	VideoXM4v                                                            MimeType = "video/x-m4v"
	VideoXMsAsf                                                          MimeType = "video/x-ms-asf"
	VideoXMsWm                                                           MimeType = "video/x-ms-wm"
	VideoXMsWmv                                                          MimeType = "video/x-ms-wmv"
	VideoXMsWmx                                                          MimeType = "video/x-ms-wmx"
	VideoXMsWvx                                                          MimeType = "video/x-ms-wvx"
	VideoXMsvideo                                                        MimeType = "video/x-msvideo"
	VideoXSgiMovie                                                       MimeType = "video/x-sgi-movie"
	XConferenceXCooltalk                                                 MimeType = "x-conference/x-cooltalk"
)

var (
	All = MimeTypes{
		ApplicationAndrewInset,
		ApplicationApplixware,
		ApplicationAtomXml,
		ApplicationAtomcatXml,
		ApplicationAtomsvcXml,
		ApplicationCcxmlXml,
		ApplicationCdmiCapability,
		ApplicationCdmiContainer,
		ApplicationCdmiDomain,
		ApplicationCdmiObject,
		ApplicationCdmiQueue,
		ApplicationCuSeeme,
		ApplicationDavmountXml,
		ApplicationDsscDer,
		ApplicationDsscXml,
		ApplicationEcmascript,
		ApplicationEmmaXml,
		ApplicationEpubZip,
		ApplicationExi,
		ApplicationFontTdpfr,
		ApplicationGpxXml,
		ApplicationGzip,
		ApplicationHyperstudio,
		ApplicationIpfix,
		ApplicationJavaArchive,
		ApplicationJavaSerializedObject,
		ApplicationJavaVm,
		ApplicationJavascript,
		ApplicationJson,
		ApplicationLdJson,
		ApplicationMacBinhex40,
		ApplicationMacCompactpro,
		ApplicationMadsXml,
		ApplicationMarc,
		ApplicationMarcxmlXml,
		ApplicationMathematica,
		ApplicationMathmlXml,
		ApplicationMbox,
		ApplicationMediaservercontrolXml,
		ApplicationMetalink4Xml,
		ApplicationMetsXml,
		ApplicationModsXml,
		ApplicationMp21,
		ApplicationMp4,
		ApplicationMsword,
		ApplicationMxf,
		ApplicationOctetStream,
		ApplicationOda,
		ApplicationOebpsPackageXml,
		ApplicationOgg,
		ApplicationOnenote,
		ApplicationPatchOpsErrorXml,
		ApplicationPdf,
		ApplicationPgpEncrypted,
		ApplicationPgpSignature,
		ApplicationPicsRules,
		ApplicationPkcs10,
		ApplicationPkcs7Mime,
		ApplicationPkcs7Signature,
		ApplicationPkcs8,
		ApplicationPkixAttrCert,
		ApplicationPkixCert,
		ApplicationPkixCrl,
		ApplicationPkixPkipath,
		ApplicationPkixcmp,
		ApplicationPlsXml,
		ApplicationPostscript,
		ApplicationPrsCww,
		ApplicationPskcXml,
		ApplicationRdfXml,
		ApplicationReginfoXml,
		ApplicationRelaxNgCompactSyntax,
		ApplicationResourceListsDiffXml,
		ApplicationResourceListsXml,
		ApplicationRlsServicesXml,
		ApplicationRsdXml,
		ApplicationRssXml,
		ApplicationRtf,
		ApplicationSbmlXml,
		ApplicationScvpCvRequest,
		ApplicationScvpCvResponse,
		ApplicationScvpVpRequest,
		ApplicationScvpVpResponse,
		ApplicationSdp,
		ApplicationSetPaymentInitiation,
		ApplicationSetRegistrationInitiation,
		ApplicationShfXml,
		ApplicationSmilXml,
		ApplicationSparqlQuery,
		ApplicationSparqlResultsXml,
		ApplicationSrgs,
		ApplicationSrgsXml,
		ApplicationSruXml,
		ApplicationSsmlXml,
		ApplicationTeiXml,
		ApplicationThraudXml,
		ApplicationTimestampedData,
		ApplicationVnd3gpp2Tcap,
		ApplicationVnd3gppPicBwLarge,
		ApplicationVnd3gppPicBwSmall,
		ApplicationVnd3gppPicBwVar,
		ApplicationVnd3mPostItNotes,
		ApplicationVndAccpacSimplyAso,
		ApplicationVndAccpacSimplyImp,
		ApplicationVndAcucobol,
		ApplicationVndAcucorp,
		ApplicationVndAdobeAirApplicationInstallerPackageZip,
		ApplicationVndAdobeFxp,
		ApplicationVndAdobeXdpXml,
		ApplicationVndAdobeXfdf,
		ApplicationVndAheadSpace,
		ApplicationVndAirzipFilesecureAzf,
		ApplicationVndAirzipFilesecureAzs,
		ApplicationVndAmazonEbook,
		ApplicationVndAmericandynamicsAcc,
		ApplicationVndAmigaAmi,
		ApplicationVndAndroidPackageArchive,
		ApplicationVndAnserWebCertificateIssueInitiation,
		ApplicationVndAnserWebFundsTransferInitiation,
		ApplicationVndAntixGameComponent,
		ApplicationVndAppleInstallerXml,
		ApplicationVndAppleMpegurl,
		ApplicationVndAristanetworksSwi,
		ApplicationVndAudiograph,
		ApplicationVndBlueiceMultipass,
		ApplicationVndBmi,
		ApplicationVndBusinessobjects,
		ApplicationVndChemdrawXml,
		ApplicationVndChipnutsKaraokeMmd,
		ApplicationVndCinderella,
		ApplicationVndClaymore,
		ApplicationVndCloantoRp9,
		ApplicationVndClonkC4group,
		ApplicationVndCluetrustCartomobileConfig,
		ApplicationVndCluetrustCartomobileConfigPkg,
		ApplicationVndCommonspace,
		ApplicationVndContactCmsg,
		ApplicationVndCosmocaller,
		ApplicationVndCrickClicker,
		ApplicationVndCrickClickerKeyboard,
		ApplicationVndCrickClickerPalette,
		ApplicationVndCrickClickerTemplate,
		ApplicationVndCrickClickerWordbank,
		ApplicationVndCriticaltoolsWbsXml,
		ApplicationVndCtcPosml,
		ApplicationVndCupsPpd,
		ApplicationVndCurlCar,
		ApplicationVndCurlPcurl,
		ApplicationVndDataVisionRdz,
		ApplicationVndDenovoFcselayoutLink,
		ApplicationVndDna,
		ApplicationVndDolbyMlp,
		ApplicationVndDpgraph,
		ApplicationVndDreamfactory,
		ApplicationVndDvbAit,
		ApplicationVndDvbService,
		ApplicationVndDynageo,
		ApplicationVndEcowinChart,
		ApplicationVndEnliven,
		ApplicationVndEpsonEsf,
		ApplicationVndEpsonMsf,
		ApplicationVndEpsonQuickanime,
		ApplicationVndEpsonSalt,
		ApplicationVndEpsonSsf,
		ApplicationVndEszigno3Xml,
		ApplicationVndEzpixAlbum,
		ApplicationVndEzpixPackage,
		ApplicationVndFdf,
		ApplicationVndFdsnSeed,
		ApplicationVndFlographit,
		ApplicationVndFluxtimeClip,
		ApplicationVndFramemaker,
		ApplicationVndFrogansFnc,
		ApplicationVndFrogansLtf,
		ApplicationVndFscWeblaunch,
		ApplicationVndFujitsuOasys,
		ApplicationVndFujitsuOasys2,
		ApplicationVndFujitsuOasys3,
		ApplicationVndFujitsuOasysgp,
		ApplicationVndFujitsuOasysprs,
		ApplicationVndFujixeroxDdd,
		ApplicationVndFujixeroxDocuworks,
		ApplicationVndFujixeroxDocuworksBinder,
		ApplicationVndFuzzysheet,
		ApplicationVndGenomatixTuxedo,
		ApplicationVndGeogebraFile,
		ApplicationVndGeogebraTool,
		ApplicationVndGeometryExplorer,
		ApplicationVndGeonext,
		ApplicationVndGeoplan,
		ApplicationVndGeospace,
		ApplicationVndGmx,
		ApplicationVndGoogleEarthKmlXml,
		ApplicationVndGoogleEarthKmz,
		ApplicationVndGrafeq,
		ApplicationVndGrooveAccount,
		ApplicationVndGrooveHelp,
		ApplicationVndGrooveIdentityMessage,
		ApplicationVndGrooveInjector,
		ApplicationVndGrooveToolMessage,
		ApplicationVndGrooveToolTemplate,
		ApplicationVndGrooveVcard,
		ApplicationVndHalXml,
		ApplicationVndHandheldEntertainmentXml,
		ApplicationVndHbci,
		ApplicationVndHheLessonPlayer,
		ApplicationVndHpHpgl,
		ApplicationVndHpHpid,
		ApplicationVndHpHps,
		ApplicationVndHpJlyt,
		ApplicationVndHpPcl,
		ApplicationVndHpPclxl,
		ApplicationVndHydrostatixSofData,
		ApplicationVndHzn3dCrossword,
		ApplicationVndIbmMinipay,
		ApplicationVndIbmModcap,
		ApplicationVndIbmRightsManagement,
		ApplicationVndIbmSecureContainer,
		ApplicationVndIccprofile,
		ApplicationVndIgloader,
		ApplicationVndImmervisionIvp,
		ApplicationVndImmervisionIvu,
		ApplicationVndInsorsIgm,
		ApplicationVndInterconFormnet,
		ApplicationVndIntergeo,
		ApplicationVndIntuQbo,
		ApplicationVndIntuQfx,
		ApplicationVndIpunpluggedRcprofile,
		ApplicationVndIrepositoryPackageXml,
		ApplicationVndIsXpr,
		ApplicationVndIsacFcs,
		ApplicationVndJam,
		ApplicationVndJcpJavameMidletRms,
		ApplicationVndJisp,
		ApplicationVndJoostJodaArchive,
		ApplicationVndKahootz,
		ApplicationVndKdeKarbon,
		ApplicationVndKdeKchart,
		ApplicationVndKdeKformula,
		ApplicationVndKdeKivio,
		ApplicationVndKdeKontour,
		ApplicationVndKdeKpresenter,
		ApplicationVndKdeKspread,
		ApplicationVndKdeKword,
		ApplicationVndKenameaapp,
		ApplicationVndKidspiration,
		ApplicationVndKinar,
		ApplicationVndKoan,
		ApplicationVndKodakDescriptor,
		ApplicationVndLasLasXml,
		ApplicationVndLlamagraphicsLifeBalanceDesktop,
		ApplicationVndLlamagraphicsLifeBalanceExchangeXml,
		ApplicationVndLotus123,
		ApplicationVndLotusApproach,
		ApplicationVndLotusFreelance,
		ApplicationVndLotusNotes,
		ApplicationVndLotusOrganizer,
		ApplicationVndLotusScreencam,
		ApplicationVndLotusWordpro,
		ApplicationVndMacportsPortpkg,
		ApplicationVndMcd,
		ApplicationVndMedcalcdata,
		ApplicationVndMediastationCdkey,
		ApplicationVndMfer,
		ApplicationVndMfmp,
		ApplicationVndMicrografxFlo,
		ApplicationVndMicrografxIgx,
		ApplicationVndMif,
		ApplicationVndMobiusDaf,
		ApplicationVndMobiusDis,
		ApplicationVndMobiusMbk,
		ApplicationVndMobiusMqy,
		ApplicationVndMobiusMsl,
		ApplicationVndMobiusPlc,
		ApplicationVndMobiusTxf,
		ApplicationVndMophunApplication,
		ApplicationVndMophunCertificate,
		ApplicationVndMozillaXulXml,
		ApplicationVndMsArtgalry,
		ApplicationVndMsCabCompressed,
		ApplicationVndMsExcel,
		ApplicationVndMsExcelAddinMacroenabled12,
		ApplicationVndMsExcelSheetBinaryMacroenabled12,
		ApplicationVndMsExcelSheetMacroenabled12,
		ApplicationVndMsExcelTemplateMacroenabled12,
		ApplicationVndMsFontobject,
		ApplicationVndMsHtmlhelp,
		ApplicationVndMsIms,
		ApplicationVndMsLrm,
		ApplicationVndMsOfficetheme,
		ApplicationVndMsPkiSeccat,
		ApplicationVndMsPkiStl,
		ApplicationVndMsPowerpoint,
		ApplicationVndMsPowerpointAddinMacroenabled12,
		ApplicationVndMsPowerpointPresentationMacroenabled12,
		ApplicationVndMsPowerpointSlideMacroenabled12,
		ApplicationVndMsPowerpointSlideshowMacroenabled12,
		ApplicationVndMsPowerpointTemplateMacroenabled12,
		ApplicationVndMsProject,
		ApplicationVndMsWordDocumentMacroenabled12,
		ApplicationVndMsWordTemplateMacroenabled12,
		ApplicationVndMsWorks,
		ApplicationVndMsWpl,
		ApplicationVndMsXpsdocument,
		ApplicationVndMseq,
		ApplicationVndMusician,
		ApplicationVndMuveeStyle,
		ApplicationVndNeurolanguageNlu,
		ApplicationVndNoblenetDirectory,
		ApplicationVndNoblenetSealer,
		ApplicationVndNoblenetWeb,
		ApplicationVndNokiaNGageData,
		ApplicationVndNokiaNGageSymbianInstall,
		ApplicationVndNokiaRadioPreset,
		ApplicationVndNokiaRadioPresets,
		ApplicationVndNovadigmEdm,
		ApplicationVndNovadigmEdx,
		ApplicationVndNovadigmExt,
		ApplicationVndOasisOpendocumentChart,
		ApplicationVndOasisOpendocumentChartTemplate,
		ApplicationVndOasisOpendocumentDatabase,
		ApplicationVndOasisOpendocumentFormula,
		ApplicationVndOasisOpendocumentFormulaTemplate,
		ApplicationVndOasisOpendocumentGraphics,
		ApplicationVndOasisOpendocumentGraphicsTemplate,
		ApplicationVndOasisOpendocumentImage,
		ApplicationVndOasisOpendocumentImageTemplate,
		ApplicationVndOasisOpendocumentPresentation,
		ApplicationVndOasisOpendocumentPresentationTemplate,
		ApplicationVndOasisOpendocumentSpreadsheet,
		ApplicationVndOasisOpendocumentSpreadsheetTemplate,
		ApplicationVndOasisOpendocumentText,
		ApplicationVndOasisOpendocumentTextMaster,
		ApplicationVndOasisOpendocumentTextTemplate,
		ApplicationVndOasisOpendocumentTextWeb,
		ApplicationVndOlpcSugar,
		ApplicationVndOmaDd2Xml,
		ApplicationVndOpenofficeorgExtension,
		ApplicationVndOpenxmlformatsOfficedocumentPresentationmlPresentation,
		ApplicationVndOpenxmlformatsOfficedocumentPresentationmlSlide,
		ApplicationVndOpenxmlformatsOfficedocumentPresentationmlSlideshow,
		ApplicationVndOpenxmlformatsOfficedocumentPresentationmlTemplate,
		ApplicationVndOpenxmlformatsOfficedocumentSpreadsheetmlSheet,
		ApplicationVndOpenxmlformatsOfficedocumentSpreadsheetmlTemplate,
		ApplicationVndOpenxmlformatsOfficedocumentWordprocessingmlDocument,
		ApplicationVndOpenxmlformatsOfficedocumentWordprocessingmlTemplate,
		ApplicationVndOsgeoMapguidePackage,
		ApplicationVndOsgiDp,
		ApplicationVndPalm,
		ApplicationVndPawaafile,
		ApplicationVndPgFormat,
		ApplicationVndPgOsasli,
		ApplicationVndPicsel,
		ApplicationVndPmiWidget,
		ApplicationVndPocketlearn,
		ApplicationVndPowerbuilder6,
		ApplicationVndPreviewsystemsBox,
		ApplicationVndProteusMagazine,
		ApplicationVndPublishareDeltaTree,
		ApplicationVndPviPtid1,
		ApplicationVndQuarkQuarkxpress,
		ApplicationVndRar,
		ApplicationVndRealvncBed,
		ApplicationVndRecordareMusicxml,
		ApplicationVndRecordareMusicxmlXml,
		ApplicationVndRigCryptonote,
		ApplicationVndRimCod,
		ApplicationVndRnRealmedia,
		ApplicationVndRoute66Link66Xml,
		ApplicationVndSailingtrackerTrack,
		ApplicationVndSeemail,
		ApplicationVndSema,
		ApplicationVndSemd,
		ApplicationVndSemf,
		ApplicationVndShanaInformedFormdata,
		ApplicationVndShanaInformedFormtemplate,
		ApplicationVndShanaInformedInterchange,
		ApplicationVndShanaInformedPackage,
		ApplicationVndSimtechMindmapper,
		ApplicationVndSmaf,
		ApplicationVndSmartTeacher,
		ApplicationVndSolentSdkmXml,
		ApplicationVndSpotfireDxp,
		ApplicationVndSpotfireSfs,
		ApplicationVndStardivisionCalc,
		ApplicationVndStardivisionDraw,
		ApplicationVndStardivisionImpress,
		ApplicationVndStardivisionMath,
		ApplicationVndStardivisionWriter,
		ApplicationVndStardivisionWriterGlobal,
		ApplicationVndStepmaniaStepchart,
		ApplicationVndSunXmlCalc,
		ApplicationVndSunXmlCalcTemplate,
		ApplicationVndSunXmlDraw,
		ApplicationVndSunXmlDrawTemplate,
		ApplicationVndSunXmlImpress,
		ApplicationVndSunXmlImpressTemplate,
		ApplicationVndSunXmlMath,
		ApplicationVndSunXmlWriter,
		ApplicationVndSunXmlWriterGlobal,
		ApplicationVndSunXmlWriterTemplate,
		ApplicationVndSusCalendar,
		ApplicationVndSvd,
		ApplicationVndSymbianInstall,
		ApplicationVndSyncmlDmWbxml,
		ApplicationVndSyncmlDmXml,
		ApplicationVndSyncmlXml,
		ApplicationVndTaoIntentModuleArchive,
		ApplicationVndTmobileLivetv,
		ApplicationVndTridTpt,
		ApplicationVndTriscapeMxs,
		ApplicationVndTrueapp,
		ApplicationVndUfdl,
		ApplicationVndUiqTheme,
		ApplicationVndUmajin,
		ApplicationVndUnity,
		ApplicationVndUomlXml,
		ApplicationVndVcx,
		ApplicationVndVisio,
		ApplicationVndVisio2013,
		ApplicationVndVisionary,
		ApplicationVndVsf,
		ApplicationVndWapWbxml,
		ApplicationVndWapWmlc,
		ApplicationVndWapWmlscriptc,
		ApplicationVndWebturbo,
		ApplicationVndWolframPlayer,
		ApplicationVndWordperfect,
		ApplicationVndWqd,
		ApplicationVndWtStf,
		ApplicationVndXara,
		ApplicationVndXfdl,
		ApplicationVndYamahaHvDic,
		ApplicationVndYamahaHvScript,
		ApplicationVndYamahaHvVoice,
		ApplicationVndYamahaOpenscoreformat,
		ApplicationVndYamahaOpenscoreformatOsfpvgXml,
		ApplicationVndYamahaSmafAudio,
		ApplicationVndYamahaSmafPhrase,
		ApplicationVndYellowriverCustomMenu,
		ApplicationVndZul,
		ApplicationVndZzazzDeckXml,
		ApplicationVoicexmlXml,
		ApplicationWidget,
		ApplicationWinhlp,
		ApplicationWsdlXml,
		ApplicationWspolicyXml,
		ApplicationX7zCompressed,
		ApplicationXAbiword,
		ApplicationXAceCompressed,
		ApplicationXAppleDiskimage,
		ApplicationXAuthorwareBin,
		ApplicationXAuthorwareMap,
		ApplicationXAuthorwareSeg,
		ApplicationXBcpio,
		ApplicationXBittorrent,
		ApplicationXBzip,
		ApplicationXBzip2,
		ApplicationXCdf,
		ApplicationXCdlink,
		ApplicationXChat,
		ApplicationXChessPgn,
		ApplicationXCpio,
		ApplicationXCsh,
		ApplicationXDebianPackage,
		ApplicationXDirector,
		ApplicationXDoom,
		ApplicationXDtbncxXml,
		ApplicationXDtbookXml,
		ApplicationXDtbresourceXml,
		ApplicationXDvi,
		ApplicationXFontBdf,
		ApplicationXFontGhostscript,
		ApplicationXFontLinuxPsf,
		ApplicationXFontOtf,
		ApplicationXFontPcf,
		ApplicationXFontSnf,
		ApplicationXFontTtf,
		ApplicationXFontType1,
		ApplicationXFontWoff,
		ApplicationXFreearc,
		ApplicationXFuturesplash,
		ApplicationXGnumeric,
		ApplicationXGtar,
		ApplicationXHdf,
		ApplicationXHttpdPhp,
		ApplicationXJavaJnlpFile,
		ApplicationXLatex,
		ApplicationXMobipocketEbook,
		ApplicationXMsApplication,
		ApplicationXMsWmd,
		ApplicationXMsWmz,
		ApplicationXMsXbap,
		ApplicationXMsaccess,
		ApplicationXMsbinder,
		ApplicationXMscardfile,
		ApplicationXMsclip,
		ApplicationXMsdownload,
		ApplicationXMsmediaview,
		ApplicationXMsmetafile,
		ApplicationXMsmoney,
		ApplicationXMspublisher,
		ApplicationXMsschedule,
		ApplicationXMsterminal,
		ApplicationXMswrite,
		ApplicationXNetcdf,
		ApplicationXPkcs12,
		ApplicationXPkcs7Certificates,
		ApplicationXPkcs7Certreqresp,
		ApplicationXRarCompressed,
		ApplicationXSh,
		ApplicationXShar,
		ApplicationXShockwaveFlash,
		ApplicationXSilverlightApp,
		ApplicationXStuffit,
		ApplicationXStuffitx,
		ApplicationXSv4cpio,
		ApplicationXSv4crc,
		ApplicationXTar,
		ApplicationXTcl,
		ApplicationXTex,
		ApplicationXTexTfm,
		ApplicationXTexinfo,
		ApplicationXUstar,
		ApplicationXWaisSource,
		ApplicationXX509CaCert,
		ApplicationXXfig,
		ApplicationXXpinstall,
		ApplicationXYaml,
		ApplicationXcapDiffXml,
		ApplicationXencXml,
		ApplicationXhtmlXml,
		ApplicationXml,
		ApplicationXmlDtd,
		ApplicationXopXml,
		ApplicationXsltXml,
		ApplicationXspfXml,
		ApplicationXvXml,
		ApplicationYang,
		ApplicationYinXml,
		ApplicationZip,
		Audio3gpp,
		Audio3gpp2,
		AudioAdpcm,
		AudioBasic,
		AudioMidi,
		AudioMp4,
		AudioMpeg,
		AudioOgg,
		AudioOpus,
		AudioVndDeceAudio,
		AudioVndDigitalWinds,
		AudioVndDra,
		AudioVndDts,
		AudioVndDtsHd,
		AudioVndLucentVoice,
		AudioVndMsPlayreadyMediaPya,
		AudioVndNueraEcelp4800,
		AudioVndNueraEcelp7470,
		AudioVndNueraEcelp9600,
		AudioVndRip,
		AudioWav,
		AudioWebm,
		AudioXAac,
		AudioXAiff,
		AudioXMidi,
		AudioXMpegurl,
		AudioXMsWax,
		AudioXMsWma,
		AudioXPnRealaudio,
		AudioXPnRealaudioPlugin,
		AudioXWav,
		ChemicalXCdx,
		ChemicalXCif,
		ChemicalXCmdf,
		ChemicalXCml,
		ChemicalXCsml,
		ChemicalXXyz,
		FontOtf,
		FontTtf,
		FontWoff,
		FontWoff2,
		ImageBmp,
		ImageCgm,
		ImageG3fax,
		ImageGif,
		ImageIef,
		ImageJpeg,
		ImageKtx,
		ImagePjpeg,
		ImagePng,
		ImagePrsBtif,
		ImageSvgXml,
		ImageTiff,
		ImageVndAdobePhotoshop,
		ImageVndDeceGraphic,
		ImageVndDjvu,
		ImageVndDvbSubtitle,
		ImageVndDwg,
		ImageVndDxf,
		ImageVndFastbidsheet,
		ImageVndFpx,
		ImageVndFst,
		ImageVndFujixeroxEdmicsMmr,
		ImageVndFujixeroxEdmicsRlc,
		ImageVndMicrosoftIcon,
		ImageVndMsModi,
		ImageVndNetFpx,
		ImageVndWapWbmp,
		ImageVndXiff,
		ImageWebp,
		ImageXCitrixJpeg,
		ImageXCitrixPng,
		ImageXCmuRaster,
		ImageXCmx,
		ImageXFreehand,
		ImageXIcon,
		ImageXPcx,
		ImageXPict,
		ImageXPng,
		ImageXPortableAnymap,
		ImageXPortableBitmap,
		ImageXPortableGraymap,
		ImageXPortablePixmap,
		ImageXRgb,
		ImageXXbitmap,
		ImageXXpixmap,
		ImageXXwindowdump,
		Java,
		MessageRfc822,
		ModelIges,
		ModelMesh,
		ModelVndColladaXml,
		ModelVndDwf,
		ModelVndGdl,
		ModelVndGtw,
		ModelVndMts,
		ModelVndVtu,
		ModelVrml,
		TextCalendar,
		TextCss,
		TextCsv,
		TextHtml,
		TextJavascript,
		TextN3,
		TextPlain,
		TextPlainBas,
		TextPrsLinesTag,
		TextRichtext,
		TextSgml,
		TextTabSeparatedValues,
		TextTroff,
		TextTurtle,
		TextUriList,
		TextVndCurl,
		TextVndCurlDcurl,
		TextVndCurlMcurl,
		TextVndCurlScurl,
		TextVndFly,
		TextVndFmiFlexstor,
		TextVndGraphviz,
		TextVndIn3d3dml,
		TextVndIn3dSpot,
		TextVndSunJ2meAppDescriptor,
		TextVndWapWml,
		TextVndWapWmlscript,
		TextXAsm,
		TextXC,
		TextXFortran,
		TextXJavaSource,
		TextXPascal,
		TextXSetext,
		TextXUuencode,
		TextXVcalendar,
		TextXVcard,
		TextXYaml,
		TextXml,
		TextYaml,
		Unkown,
		Video3gpp,
		Video3gpp2,
		VideoH261,
		VideoH263,
		VideoH264,
		VideoJpeg,
		VideoJpm,
		VideoMj2,
		VideoMp2t,
		VideoMp4,
		VideoMpeg,
		VideoOgg,
		VideoQuicktime,
		VideoVndDeceHd,
		VideoVndDeceMobile,
		VideoVndDecePd,
		VideoVndDeceSd,
		VideoVndDeceVideo,
		VideoVndFvt,
		VideoVndMpegurl,
		VideoVndMsPlayreadyMediaPyv,
		VideoVndUvvuMp4,
		VideoVndVivo,
		VideoWebm,
		VideoXF4v,
		VideoXFli,
		VideoXFlv,
		VideoXM4v,
		VideoXMsAsf,
		VideoXMsWm,
		VideoXMsWmv,
		VideoXMsWmx,
		VideoXMsWvx,
		VideoXMsvideo,
		VideoXSgiMovie,
		XConferenceXCooltalk,
	}
)

func Is(v string) bool {
	return All.Is(v)
}

func Parse(v string) (MimeType, error) {
	return All.Parse(v)
}

func Strings() []string {
	return All.Strings()
}

func (t MimeType) String() string {
	return string(t)
}

var ErrMimeTypeInvalid = errors.New("invalid enumeration type")

func Error(vs MimeTypes, v string) error {
	return fmt.Errorf(
		"%w '%v', must be one of %v",
		ErrMimeTypeInvalid, v, strings.Join(vs.Strings(), ","),
	)
}

func (t MimeTypes) Strings() []string {
	var ss []string

	for _, v := range t {
		ss = append(ss, v.String())
	}

	return ss
}

func (t MimeTypes) Parse(v string) (MimeType, error) {
	var o MimeType
	var f bool
	n := strings.ToLower(v)

	for _, e := range t {
		if strings.ToLower(e.String()) == n {
			o = e
			f = true
			break
		}
	}

	if !f {
		return o, Error(t, v)
	}

	return o, nil
}

func (t MimeTypes) Is(v string) bool {
	var f bool

	for _, e := range t {
		if string(e) == v {
			f = true
			break
		}
	}

	return f
}

func (t MimeTypes) Contains(v MimeType) bool {
	for _, e := range t {
		if e == v {
			return true
		}
	}

	return false
}

func (t MimeType) MarshalJSON() ([]byte, error) {
	return json.Marshal(string(t))
}

func (t *MimeType) UnmarshalJSON(data []byte) error {
	var s string

	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}

	e, err := Parse(s)

	if err != nil {
		return err
	}

	*t = e

	return nil
}
