//************************************************************************************
//*                                                                                  *
//* ===== DO NOT EDIT =====                                                          *
//* Any change will be overwritten                                                   *
//* Generated by gen/process.go                                                      *
//*                                                                                  *
//************************************************************************************

package mime_type

var (
	m = map[MimeType]MimeType{
		TextJavascript:            "ApplicationJavascript",
		ApplicationPgpSignature:   "ApplicationPgpEncrypted",
		ApplicationXRarCompressed: "ApplicationVndRar",
		TextXYaml:                 "ApplicationXYaml",
		TextYaml:                  "ApplicationXYaml",
		ApplicationYaml:           "ApplicationXYaml",
		TextXml:                   "ApplicationXml",
		AudioXMidi:                "AudioMidi",
		AudioXWav:                 "AudioWav",
		ApplicationXFontOtf:       "FontOtf",
		ApplicationXFontTtf:       "FontTtf",
		ApplicationXFontWoff:      "FontWoff",
		ImageXCitrixJpeg:          "ImageJpeg",
		ImageXCitrixPng:           "ImagePng",
		ImageXPng:                 "ImagePng",
		ImageVndMicrosoftIcon:     "ImageXIcon",
		Java:                      "TextXJavaSource",
		Audio3gpp:                 "Video3gpp",
		Audio3gpp2:                "Video3gpp2",
		ApplicationMp4:            "VideoMp4",
	}
)
