//************************************************************************************
//*                                                                                  *
//* ===== DO NOT EDIT =====                                                          *
//* Any change will be overwritten                                                   *
//* Generated by gen/process.go                                                      *
//*                                                                                  *
//************************************************************************************

package file_extention

import "github.com/boundedinfinity/mimetyper/mime_type"

var (
	ext2mt = map[FileExtention]mime_type.MimeType{
		Aw:          mime_type.ApplicationApplixware,
		Atom:        mime_type.ApplicationAtomXml,
		Atomcat:     mime_type.ApplicationAtomcatXml,
		Atomsvc:     mime_type.ApplicationAtomsvcXml,
		Ccxml:       mime_type.ApplicationCcxmlXml,
		Cdmia:       mime_type.ApplicationCdmiCapability,
		Cdmic:       mime_type.ApplicationCdmiContainer,
		Cdmid:       mime_type.ApplicationCdmiDomain,
		Cdmio:       mime_type.ApplicationCdmiObject,
		Cdmiq:       mime_type.ApplicationCdmiQueue,
		Cu:          mime_type.ApplicationCuSeeme,
		Davmount:    mime_type.ApplicationDavmountXml,
		Dssc:        mime_type.ApplicationDsscDer,
		Xdssc:       mime_type.ApplicationDsscXml,
		Es:          mime_type.ApplicationEcmascript,
		Emma:        mime_type.ApplicationEmmaXml,
		Epub:        mime_type.ApplicationEpubZip,
		Exi:         mime_type.ApplicationExi,
		Pfr:         mime_type.ApplicationFontTdpfr,
		Gpx:         mime_type.ApplicationGpxXml,
		Gz:          mime_type.ApplicationGzip,
		Stk:         mime_type.ApplicationHyperstudio,
		Ipfix:       mime_type.ApplicationIpfix,
		Jar:         mime_type.ApplicationJavaArchive,
		Ser:         mime_type.ApplicationJavaSerializedObject,
		Class:       mime_type.ApplicationJavaVm,
		Js:          mime_type.ApplicationJavascript,
		Json:        mime_type.ApplicationJson,
		Jsonld:      mime_type.ApplicationLdJson,
		Hqx:         mime_type.ApplicationMacBinhex40,
		Cpt:         mime_type.ApplicationMacCompactpro,
		Mads:        mime_type.ApplicationMadsXml,
		Mrc:         mime_type.ApplicationMarc,
		Mrcx:        mime_type.ApplicationMarcxmlXml,
		Ma:          mime_type.ApplicationMathematica,
		Mathml:      mime_type.ApplicationMathmlXml,
		Mbox:        mime_type.ApplicationMbox,
		Mscml:       mime_type.ApplicationMediaservercontrolXml,
		Meta4:       mime_type.ApplicationMetalink4Xml,
		Mets:        mime_type.ApplicationMetsXml,
		Mods:        mime_type.ApplicationModsXml,
		M21:         mime_type.ApplicationMp21,
		Doc:         mime_type.ApplicationMsword,
		Mxf:         mime_type.ApplicationMxf,
		Bin:         mime_type.ApplicationOctetStream,
		Oda:         mime_type.ApplicationOda,
		Opf:         mime_type.ApplicationOebpsPackageXml,
		Ogx:         mime_type.ApplicationOgg,
		Onetoc:      mime_type.ApplicationOnenote,
		Xer:         mime_type.ApplicationPatchOpsErrorXml,
		Pdf:         mime_type.ApplicationPdf,
		Pgp:         mime_type.ApplicationPgpEncrypted,
		Prf:         mime_type.ApplicationPicsRules,
		P10:         mime_type.ApplicationPkcs10,
		P7m:         mime_type.ApplicationPkcs7Mime,
		P7s:         mime_type.ApplicationPkcs7Signature,
		P8:          mime_type.ApplicationPkcs8,
		Ac:          mime_type.ApplicationPkixAttrCert,
		Cer:         mime_type.ApplicationPkixCert,
		Crl:         mime_type.ApplicationPkixCrl,
		Pkipath:     mime_type.ApplicationPkixPkipath,
		Pki:         mime_type.ApplicationPkixcmp,
		Pls:         mime_type.ApplicationPlsXml,
		Ai:          mime_type.ApplicationPostscript,
		Cww:         mime_type.ApplicationPrsCww,
		Pskcxml:     mime_type.ApplicationPskcXml,
		Rdf:         mime_type.ApplicationRdfXml,
		Rif:         mime_type.ApplicationReginfoXml,
		Rnc:         mime_type.ApplicationRelaxNgCompactSyntax,
		Rl:          mime_type.ApplicationResourceListsXml,
		Rld:         mime_type.ApplicationResourceListsDiffXml,
		Rs:          mime_type.ApplicationRlsServicesXml,
		Rsd:         mime_type.ApplicationRsdXml,
		Rss:         mime_type.ApplicationRssXml,
		Rtf:         mime_type.ApplicationRtf,
		Sbml:        mime_type.ApplicationSbmlXml,
		Scq:         mime_type.ApplicationScvpCvRequest,
		Scs:         mime_type.ApplicationScvpCvResponse,
		Spq:         mime_type.ApplicationScvpVpRequest,
		Spp:         mime_type.ApplicationScvpVpResponse,
		Sdp:         mime_type.ApplicationSdp,
		Setpay:      mime_type.ApplicationSetPaymentInitiation,
		Setreg:      mime_type.ApplicationSetRegistrationInitiation,
		Shf:         mime_type.ApplicationShfXml,
		Smi:         mime_type.ApplicationSmilXml,
		Rq:          mime_type.ApplicationSparqlQuery,
		Srx:         mime_type.ApplicationSparqlResultsXml,
		Gram:        mime_type.ApplicationSrgs,
		Grxml:       mime_type.ApplicationSrgsXml,
		Sru:         mime_type.ApplicationSruXml,
		Ssml:        mime_type.ApplicationSsmlXml,
		Tei:         mime_type.ApplicationTeiXml,
		Tfi:         mime_type.ApplicationThraudXml,
		Tsd:         mime_type.ApplicationTimestampedData,
		Plb:         mime_type.ApplicationVnd3gppPicBwLarge,
		Psb:         mime_type.ApplicationVnd3gppPicBwSmall,
		Pvb:         mime_type.ApplicationVnd3gppPicBwVar,
		Tcap:        mime_type.ApplicationVnd3gpp2Tcap,
		Pwn:         mime_type.ApplicationVnd3mPostItNotes,
		Aso:         mime_type.ApplicationVndAccpacSimplyAso,
		Imp:         mime_type.ApplicationVndAccpacSimplyImp,
		Acu:         mime_type.ApplicationVndAcucobol,
		Atc:         mime_type.ApplicationVndAcucorp,
		Air:         mime_type.ApplicationVndAdobeAirApplicationInstallerPackageZip,
		Fxp:         mime_type.ApplicationVndAdobeFxp,
		Xdp:         mime_type.ApplicationVndAdobeXdpXml,
		Xfdf:        mime_type.ApplicationVndAdobeXfdf,
		Ahead:       mime_type.ApplicationVndAheadSpace,
		Azf:         mime_type.ApplicationVndAirzipFilesecureAzf,
		Azs:         mime_type.ApplicationVndAirzipFilesecureAzs,
		Azw:         mime_type.ApplicationVndAmazonEbook,
		Acc:         mime_type.ApplicationVndAmericandynamicsAcc,
		Ami:         mime_type.ApplicationVndAmigaAmi,
		Apk:         mime_type.ApplicationVndAndroidPackageArchive,
		Cii:         mime_type.ApplicationVndAnserWebCertificateIssueInitiation,
		Fti:         mime_type.ApplicationVndAnserWebFundsTransferInitiation,
		Atx:         mime_type.ApplicationVndAntixGameComponent,
		Mpkg:        mime_type.ApplicationVndAppleInstallerXml,
		M3u8:        mime_type.ApplicationVndAppleMpegurl,
		Swi:         mime_type.ApplicationVndAristanetworksSwi,
		Aep:         mime_type.ApplicationVndAudiograph,
		Mpm:         mime_type.ApplicationVndBlueiceMultipass,
		Bmi:         mime_type.ApplicationVndBmi,
		Rep:         mime_type.ApplicationVndBusinessobjects,
		Cdxml:       mime_type.ApplicationVndChemdrawXml,
		Mmd:         mime_type.ApplicationVndChipnutsKaraokeMmd,
		Cdy:         mime_type.ApplicationVndCinderella,
		Cla:         mime_type.ApplicationVndClaymore,
		Rp9:         mime_type.ApplicationVndCloantoRp9,
		C4g:         mime_type.ApplicationVndClonkC4group,
		C11amc:      mime_type.ApplicationVndCluetrustCartomobileConfig,
		C11amz:      mime_type.ApplicationVndCluetrustCartomobileConfigPkg,
		Csp:         mime_type.ApplicationVndCommonspace,
		Cdbcmsg:     mime_type.ApplicationVndContactCmsg,
		Cmc:         mime_type.ApplicationVndCosmocaller,
		Clkx:        mime_type.ApplicationVndCrickClicker,
		Clkk:        mime_type.ApplicationVndCrickClickerKeyboard,
		Clkp:        mime_type.ApplicationVndCrickClickerPalette,
		Clkt:        mime_type.ApplicationVndCrickClickerTemplate,
		Clkw:        mime_type.ApplicationVndCrickClickerWordbank,
		Wbs:         mime_type.ApplicationVndCriticaltoolsWbsXml,
		Pml:         mime_type.ApplicationVndCtcPosml,
		Ppd:         mime_type.ApplicationVndCupsPpd,
		Car:         mime_type.ApplicationVndCurlCar,
		Pcurl:       mime_type.ApplicationVndCurlPcurl,
		Rdz:         mime_type.ApplicationVndDataVisionRdz,
		Fe_launch:   mime_type.ApplicationVndDenovoFcselayoutLink,
		Dna:         mime_type.ApplicationVndDna,
		Mlp:         mime_type.ApplicationVndDolbyMlp,
		Dpg:         mime_type.ApplicationVndDpgraph,
		Dfac:        mime_type.ApplicationVndDreamfactory,
		Ait:         mime_type.ApplicationVndDvbAit,
		Svc:         mime_type.ApplicationVndDvbService,
		Geo:         mime_type.ApplicationVndDynageo,
		Mag:         mime_type.ApplicationVndEcowinChart,
		Nml:         mime_type.ApplicationVndEnliven,
		Esf:         mime_type.ApplicationVndEpsonEsf,
		Msf:         mime_type.ApplicationVndEpsonMsf,
		Qam:         mime_type.ApplicationVndEpsonQuickanime,
		Slt:         mime_type.ApplicationVndEpsonSalt,
		Ssf:         mime_type.ApplicationVndEpsonSsf,
		Es3:         mime_type.ApplicationVndEszigno3Xml,
		Ez2:         mime_type.ApplicationVndEzpixAlbum,
		Ez3:         mime_type.ApplicationVndEzpixPackage,
		Fdf:         mime_type.ApplicationVndFdf,
		Seed:        mime_type.ApplicationVndFdsnSeed,
		Gph:         mime_type.ApplicationVndFlographit,
		Ftc:         mime_type.ApplicationVndFluxtimeClip,
		Fm:          mime_type.ApplicationVndFramemaker,
		Fnc:         mime_type.ApplicationVndFrogansFnc,
		Ltf:         mime_type.ApplicationVndFrogansLtf,
		Fsc:         mime_type.ApplicationVndFscWeblaunch,
		Oas:         mime_type.ApplicationVndFujitsuOasys,
		Oa2:         mime_type.ApplicationVndFujitsuOasys2,
		Oa3:         mime_type.ApplicationVndFujitsuOasys3,
		Fg5:         mime_type.ApplicationVndFujitsuOasysgp,
		Bh2:         mime_type.ApplicationVndFujitsuOasysprs,
		Ddd:         mime_type.ApplicationVndFujixeroxDdd,
		Xdw:         mime_type.ApplicationVndFujixeroxDocuworks,
		Xbd:         mime_type.ApplicationVndFujixeroxDocuworksBinder,
		Fzs:         mime_type.ApplicationVndFuzzysheet,
		Txd:         mime_type.ApplicationVndGenomatixTuxedo,
		Ggb:         mime_type.ApplicationVndGeogebraFile,
		Ggt:         mime_type.ApplicationVndGeogebraTool,
		Gex:         mime_type.ApplicationVndGeometryExplorer,
		Gxt:         mime_type.ApplicationVndGeonext,
		G2w:         mime_type.ApplicationVndGeoplan,
		G3w:         mime_type.ApplicationVndGeospace,
		Gmx:         mime_type.ApplicationVndGmx,
		Kml:         mime_type.ApplicationVndGoogleEarthKmlXml,
		Kmz:         mime_type.ApplicationVndGoogleEarthKmz,
		Gqf:         mime_type.ApplicationVndGrafeq,
		Gac:         mime_type.ApplicationVndGrooveAccount,
		Ghf:         mime_type.ApplicationVndGrooveHelp,
		Gim:         mime_type.ApplicationVndGrooveIdentityMessage,
		Grv:         mime_type.ApplicationVndGrooveInjector,
		Gtm:         mime_type.ApplicationVndGrooveToolMessage,
		Tpl:         mime_type.ApplicationVndGrooveToolTemplate,
		Vcg:         mime_type.ApplicationVndGrooveVcard,
		Hal:         mime_type.ApplicationVndHalXml,
		Zmm:         mime_type.ApplicationVndHandheldEntertainmentXml,
		Hbci:        mime_type.ApplicationVndHbci,
		Les:         mime_type.ApplicationVndHheLessonPlayer,
		Hpgl:        mime_type.ApplicationVndHpHpgl,
		Hpid:        mime_type.ApplicationVndHpHpid,
		Hps:         mime_type.ApplicationVndHpHps,
		Jlt:         mime_type.ApplicationVndHpJlyt,
		Pcl:         mime_type.ApplicationVndHpPcl,
		Pclxl:       mime_type.ApplicationVndHpPclxl,
		SfdHdstx:    mime_type.ApplicationVndHydrostatixSofData,
		X3d:         mime_type.ApplicationVndHzn3dCrossword,
		Mpy:         mime_type.ApplicationVndIbmMinipay,
		Afp:         mime_type.ApplicationVndIbmModcap,
		Irm:         mime_type.ApplicationVndIbmRightsManagement,
		Sc:          mime_type.ApplicationVndIbmSecureContainer,
		Icc:         mime_type.ApplicationVndIccprofile,
		Igl:         mime_type.ApplicationVndIgloader,
		Ivp:         mime_type.ApplicationVndImmervisionIvp,
		Ivu:         mime_type.ApplicationVndImmervisionIvu,
		Igm:         mime_type.ApplicationVndInsorsIgm,
		Xpw:         mime_type.ApplicationVndInterconFormnet,
		I2g:         mime_type.ApplicationVndIntergeo,
		Qbo:         mime_type.ApplicationVndIntuQbo,
		Qfx:         mime_type.ApplicationVndIntuQfx,
		Rcprofile:   mime_type.ApplicationVndIpunpluggedRcprofile,
		Irp:         mime_type.ApplicationVndIrepositoryPackageXml,
		Xpr:         mime_type.ApplicationVndIsXpr,
		Fcs:         mime_type.ApplicationVndIsacFcs,
		Jam:         mime_type.ApplicationVndJam,
		Rms:         mime_type.ApplicationVndJcpJavameMidletRms,
		Jisp:        mime_type.ApplicationVndJisp,
		Joda:        mime_type.ApplicationVndJoostJodaArchive,
		Ktz:         mime_type.ApplicationVndKahootz,
		Karbon:      mime_type.ApplicationVndKdeKarbon,
		Chrt:        mime_type.ApplicationVndKdeKchart,
		Kfo:         mime_type.ApplicationVndKdeKformula,
		Flw:         mime_type.ApplicationVndKdeKivio,
		Kon:         mime_type.ApplicationVndKdeKontour,
		Kpr:         mime_type.ApplicationVndKdeKpresenter,
		Ksp:         mime_type.ApplicationVndKdeKspread,
		Kwd:         mime_type.ApplicationVndKdeKword,
		Htke:        mime_type.ApplicationVndKenameaapp,
		Kia:         mime_type.ApplicationVndKidspiration,
		Kne:         mime_type.ApplicationVndKinar,
		Skp:         mime_type.ApplicationVndKoan,
		Sse:         mime_type.ApplicationVndKodakDescriptor,
		Lasxml:      mime_type.ApplicationVndLasLasXml,
		Lbd:         mime_type.ApplicationVndLlamagraphicsLifeBalanceDesktop,
		Lbe:         mime_type.ApplicationVndLlamagraphicsLifeBalanceExchangeXml,
		_123:        mime_type.ApplicationVndLotus123,
		Apr:         mime_type.ApplicationVndLotusApproach,
		Pre:         mime_type.ApplicationVndLotusFreelance,
		Nsf:         mime_type.ApplicationVndLotusNotes,
		Org:         mime_type.ApplicationVndLotusOrganizer,
		Scm:         mime_type.ApplicationVndLotusScreencam,
		Lwp:         mime_type.ApplicationVndLotusWordpro,
		Portpkg:     mime_type.ApplicationVndMacportsPortpkg,
		Mcd:         mime_type.ApplicationVndMcd,
		Mc1:         mime_type.ApplicationVndMedcalcdata,
		Cdkey:       mime_type.ApplicationVndMediastationCdkey,
		Mwf:         mime_type.ApplicationVndMfer,
		Mfm:         mime_type.ApplicationVndMfmp,
		Flo:         mime_type.ApplicationVndMicrografxFlo,
		Igx:         mime_type.ApplicationVndMicrografxIgx,
		Mif:         mime_type.ApplicationVndMif,
		Daf:         mime_type.ApplicationVndMobiusDaf,
		Dis:         mime_type.ApplicationVndMobiusDis,
		Mbk:         mime_type.ApplicationVndMobiusMbk,
		Mqy:         mime_type.ApplicationVndMobiusMqy,
		Msl:         mime_type.ApplicationVndMobiusMsl,
		Plc:         mime_type.ApplicationVndMobiusPlc,
		Txf:         mime_type.ApplicationVndMobiusTxf,
		Mpn:         mime_type.ApplicationVndMophunApplication,
		Mpc:         mime_type.ApplicationVndMophunCertificate,
		Xul:         mime_type.ApplicationVndMozillaXulXml,
		Cil:         mime_type.ApplicationVndMsArtgalry,
		Cab:         mime_type.ApplicationVndMsCabCompressed,
		Xls:         mime_type.ApplicationVndMsExcel,
		Xlam:        mime_type.ApplicationVndMsExcelAddinMacroenabled12,
		Xlsb:        mime_type.ApplicationVndMsExcelSheetBinaryMacroenabled12,
		Xlsm:        mime_type.ApplicationVndMsExcelSheetMacroenabled12,
		Xltm:        mime_type.ApplicationVndMsExcelTemplateMacroenabled12,
		Eot:         mime_type.ApplicationVndMsFontobject,
		Chm:         mime_type.ApplicationVndMsHtmlhelp,
		Ims:         mime_type.ApplicationVndMsIms,
		Lrm:         mime_type.ApplicationVndMsLrm,
		Thmx:        mime_type.ApplicationVndMsOfficetheme,
		Cat:         mime_type.ApplicationVndMsPkiSeccat,
		Stl:         mime_type.ApplicationVndMsPkiStl,
		Ppt:         mime_type.ApplicationVndMsPowerpoint,
		Ppam:        mime_type.ApplicationVndMsPowerpointAddinMacroenabled12,
		Pptm:        mime_type.ApplicationVndMsPowerpointPresentationMacroenabled12,
		Sldm:        mime_type.ApplicationVndMsPowerpointSlideMacroenabled12,
		Ppsm:        mime_type.ApplicationVndMsPowerpointSlideshowMacroenabled12,
		Potm:        mime_type.ApplicationVndMsPowerpointTemplateMacroenabled12,
		Mpp:         mime_type.ApplicationVndMsProject,
		Docm:        mime_type.ApplicationVndMsWordDocumentMacroenabled12,
		Dotm:        mime_type.ApplicationVndMsWordTemplateMacroenabled12,
		Wps:         mime_type.ApplicationVndMsWorks,
		Wpl:         mime_type.ApplicationVndMsWpl,
		Xps:         mime_type.ApplicationVndMsXpsdocument,
		Mseq:        mime_type.ApplicationVndMseq,
		Mus:         mime_type.ApplicationVndMusician,
		Msty:        mime_type.ApplicationVndMuveeStyle,
		Nlu:         mime_type.ApplicationVndNeurolanguageNlu,
		Nnd:         mime_type.ApplicationVndNoblenetDirectory,
		Nns:         mime_type.ApplicationVndNoblenetSealer,
		Nnw:         mime_type.ApplicationVndNoblenetWeb,
		Ngdat:       mime_type.ApplicationVndNokiaNGageData,
		NGage:       mime_type.ApplicationVndNokiaNGageSymbianInstall,
		Rpst:        mime_type.ApplicationVndNokiaRadioPreset,
		Rpss:        mime_type.ApplicationVndNokiaRadioPresets,
		Edm:         mime_type.ApplicationVndNovadigmEdm,
		Edx:         mime_type.ApplicationVndNovadigmEdx,
		Ext:         mime_type.ApplicationVndNovadigmExt,
		Odc:         mime_type.ApplicationVndOasisOpendocumentChart,
		Otc:         mime_type.ApplicationVndOasisOpendocumentChartTemplate,
		Odb:         mime_type.ApplicationVndOasisOpendocumentDatabase,
		Odf:         mime_type.ApplicationVndOasisOpendocumentFormula,
		Odft:        mime_type.ApplicationVndOasisOpendocumentFormulaTemplate,
		Odg:         mime_type.ApplicationVndOasisOpendocumentGraphics,
		Otg:         mime_type.ApplicationVndOasisOpendocumentGraphicsTemplate,
		Odi:         mime_type.ApplicationVndOasisOpendocumentImage,
		Oti:         mime_type.ApplicationVndOasisOpendocumentImageTemplate,
		Odp:         mime_type.ApplicationVndOasisOpendocumentPresentation,
		Otp:         mime_type.ApplicationVndOasisOpendocumentPresentationTemplate,
		Ods:         mime_type.ApplicationVndOasisOpendocumentSpreadsheet,
		Ots:         mime_type.ApplicationVndOasisOpendocumentSpreadsheetTemplate,
		Odt:         mime_type.ApplicationVndOasisOpendocumentText,
		Odm:         mime_type.ApplicationVndOasisOpendocumentTextMaster,
		Ott:         mime_type.ApplicationVndOasisOpendocumentTextTemplate,
		Oth:         mime_type.ApplicationVndOasisOpendocumentTextWeb,
		Xo:          mime_type.ApplicationVndOlpcSugar,
		Dd2:         mime_type.ApplicationVndOmaDd2Xml,
		Oxt:         mime_type.ApplicationVndOpenofficeorgExtension,
		Pptx:        mime_type.ApplicationVndOpenxmlformatsOfficedocumentPresentationmlPresentation,
		Sldx:        mime_type.ApplicationVndOpenxmlformatsOfficedocumentPresentationmlSlide,
		Ppsx:        mime_type.ApplicationVndOpenxmlformatsOfficedocumentPresentationmlSlideshow,
		Potx:        mime_type.ApplicationVndOpenxmlformatsOfficedocumentPresentationmlTemplate,
		Xlsx:        mime_type.ApplicationVndOpenxmlformatsOfficedocumentSpreadsheetmlSheet,
		Xltx:        mime_type.ApplicationVndOpenxmlformatsOfficedocumentSpreadsheetmlTemplate,
		Docx:        mime_type.ApplicationVndOpenxmlformatsOfficedocumentWordprocessingmlDocument,
		Dotx:        mime_type.ApplicationVndOpenxmlformatsOfficedocumentWordprocessingmlTemplate,
		Mgp:         mime_type.ApplicationVndOsgeoMapguidePackage,
		Dp:          mime_type.ApplicationVndOsgiDp,
		Pdb:         mime_type.ApplicationVndPalm,
		Paw:         mime_type.ApplicationVndPawaafile,
		Str:         mime_type.ApplicationVndPgFormat,
		Ei6:         mime_type.ApplicationVndPgOsasli,
		Efif:        mime_type.ApplicationVndPicsel,
		Wg:          mime_type.ApplicationVndPmiWidget,
		Plf:         mime_type.ApplicationVndPocketlearn,
		Pbd:         mime_type.ApplicationVndPowerbuilder6,
		Box:         mime_type.ApplicationVndPreviewsystemsBox,
		Mgz:         mime_type.ApplicationVndProteusMagazine,
		Qps:         mime_type.ApplicationVndPublishareDeltaTree,
		Ptid:        mime_type.ApplicationVndPviPtid1,
		Qxd:         mime_type.ApplicationVndQuarkQuarkxpress,
		Rar:         mime_type.ApplicationVndRar,
		Bed:         mime_type.ApplicationVndRealvncBed,
		Mxl:         mime_type.ApplicationVndRecordareMusicxml,
		Musicxml:    mime_type.ApplicationVndRecordareMusicxmlXml,
		Cryptonote:  mime_type.ApplicationVndRigCryptonote,
		Cod:         mime_type.ApplicationVndRimCod,
		Rm:          mime_type.ApplicationVndRnRealmedia,
		Link66:      mime_type.ApplicationVndRoute66Link66Xml,
		St:          mime_type.ApplicationVndSailingtrackerTrack,
		See:         mime_type.ApplicationVndSeemail,
		Sema:        mime_type.ApplicationVndSema,
		Semd:        mime_type.ApplicationVndSemd,
		Semf:        mime_type.ApplicationVndSemf,
		Ifm:         mime_type.ApplicationVndShanaInformedFormdata,
		Itp:         mime_type.ApplicationVndShanaInformedFormtemplate,
		Iif:         mime_type.ApplicationVndShanaInformedInterchange,
		Ipk:         mime_type.ApplicationVndShanaInformedPackage,
		Twd:         mime_type.ApplicationVndSimtechMindmapper,
		Mmf:         mime_type.ApplicationVndSmaf,
		Teacher:     mime_type.ApplicationVndSmartTeacher,
		Sdkm:        mime_type.ApplicationVndSolentSdkmXml,
		Dxp:         mime_type.ApplicationVndSpotfireDxp,
		Sfs:         mime_type.ApplicationVndSpotfireSfs,
		Sdc:         mime_type.ApplicationVndStardivisionCalc,
		Sda:         mime_type.ApplicationVndStardivisionDraw,
		Sdd:         mime_type.ApplicationVndStardivisionImpress,
		Smf:         mime_type.ApplicationVndStardivisionMath,
		Sdw:         mime_type.ApplicationVndStardivisionWriter,
		Sgl:         mime_type.ApplicationVndStardivisionWriterGlobal,
		Sm:          mime_type.ApplicationVndStepmaniaStepchart,
		Sxc:         mime_type.ApplicationVndSunXmlCalc,
		Stc:         mime_type.ApplicationVndSunXmlCalcTemplate,
		Sxd:         mime_type.ApplicationVndSunXmlDraw,
		Std:         mime_type.ApplicationVndSunXmlDrawTemplate,
		Sxi:         mime_type.ApplicationVndSunXmlImpress,
		Sti:         mime_type.ApplicationVndSunXmlImpressTemplate,
		Sxm:         mime_type.ApplicationVndSunXmlMath,
		Sxw:         mime_type.ApplicationVndSunXmlWriter,
		Sxg:         mime_type.ApplicationVndSunXmlWriterGlobal,
		Stw:         mime_type.ApplicationVndSunXmlWriterTemplate,
		Sus:         mime_type.ApplicationVndSusCalendar,
		Svd:         mime_type.ApplicationVndSvd,
		Sis:         mime_type.ApplicationVndSymbianInstall,
		Xsm:         mime_type.ApplicationVndSyncmlXml,
		Bdm:         mime_type.ApplicationVndSyncmlDmWbxml,
		Xdm:         mime_type.ApplicationVndSyncmlDmXml,
		Tao:         mime_type.ApplicationVndTaoIntentModuleArchive,
		Tmo:         mime_type.ApplicationVndTmobileLivetv,
		Tpt:         mime_type.ApplicationVndTridTpt,
		Mxs:         mime_type.ApplicationVndTriscapeMxs,
		Tra:         mime_type.ApplicationVndTrueapp,
		Ufd:         mime_type.ApplicationVndUfdl,
		Utz:         mime_type.ApplicationVndUiqTheme,
		Umj:         mime_type.ApplicationVndUmajin,
		Unityweb:    mime_type.ApplicationVndUnity,
		Uoml:        mime_type.ApplicationVndUomlXml,
		Vcx:         mime_type.ApplicationVndVcx,
		Vsd:         mime_type.ApplicationVndVisio,
		Vsdx:        mime_type.ApplicationVndVisio2013,
		Vis:         mime_type.ApplicationVndVisionary,
		Vsf:         mime_type.ApplicationVndVsf,
		Wbxml:       mime_type.ApplicationVndWapWbxml,
		Wmlc:        mime_type.ApplicationVndWapWmlc,
		Wmlsc:       mime_type.ApplicationVndWapWmlscriptc,
		Wtb:         mime_type.ApplicationVndWebturbo,
		Nbp:         mime_type.ApplicationVndWolframPlayer,
		Wpd:         mime_type.ApplicationVndWordperfect,
		Wqd:         mime_type.ApplicationVndWqd,
		Stf:         mime_type.ApplicationVndWtStf,
		Xar:         mime_type.ApplicationVndXara,
		Xfdl:        mime_type.ApplicationVndXfdl,
		Hvd:         mime_type.ApplicationVndYamahaHvDic,
		Hvs:         mime_type.ApplicationVndYamahaHvScript,
		Hvp:         mime_type.ApplicationVndYamahaHvVoice,
		Osf:         mime_type.ApplicationVndYamahaOpenscoreformat,
		Osfpvg:      mime_type.ApplicationVndYamahaOpenscoreformatOsfpvgXml,
		Saf:         mime_type.ApplicationVndYamahaSmafAudio,
		Spf:         mime_type.ApplicationVndYamahaSmafPhrase,
		Cmp:         mime_type.ApplicationVndYellowriverCustomMenu,
		Zir:         mime_type.ApplicationVndZul,
		Zaz:         mime_type.ApplicationVndZzazzDeckXml,
		Vxml:        mime_type.ApplicationVoicexmlXml,
		Wgt:         mime_type.ApplicationWidget,
		Hlp:         mime_type.ApplicationWinhlp,
		Wsdl:        mime_type.ApplicationWsdlXml,
		Wspolicy:    mime_type.ApplicationWspolicyXml,
		_7z:         mime_type.ApplicationX7zCompressed,
		Abw:         mime_type.ApplicationXAbiword,
		Ace:         mime_type.ApplicationXAceCompressed,
		Dmg:         mime_type.ApplicationXAppleDiskimage,
		Aab:         mime_type.ApplicationXAuthorwareBin,
		Aam:         mime_type.ApplicationXAuthorwareMap,
		Aas:         mime_type.ApplicationXAuthorwareSeg,
		Bcpio:       mime_type.ApplicationXBcpio,
		Torrent:     mime_type.ApplicationXBittorrent,
		Bz:          mime_type.ApplicationXBzip,
		Bz2:         mime_type.ApplicationXBzip2,
		Cda:         mime_type.ApplicationXCdf,
		Vcd:         mime_type.ApplicationXCdlink,
		Chat:        mime_type.ApplicationXChat,
		Pgn:         mime_type.ApplicationXChessPgn,
		Cpio:        mime_type.ApplicationXCpio,
		Csh:         mime_type.ApplicationXCsh,
		Deb:         mime_type.ApplicationXDebianPackage,
		Dir:         mime_type.ApplicationXDirector,
		Wad:         mime_type.ApplicationXDoom,
		Ncx:         mime_type.ApplicationXDtbncxXml,
		Dtb:         mime_type.ApplicationXDtbookXml,
		Res:         mime_type.ApplicationXDtbresourceXml,
		Dvi:         mime_type.ApplicationXDvi,
		Bdf:         mime_type.ApplicationXFontBdf,
		Gsf:         mime_type.ApplicationXFontGhostscript,
		Psf:         mime_type.ApplicationXFontLinuxPsf,
		Pcf:         mime_type.ApplicationXFontPcf,
		Snf:         mime_type.ApplicationXFontSnf,
		Pfa:         mime_type.ApplicationXFontType1,
		Arc:         mime_type.ApplicationXFreearc,
		Spl:         mime_type.ApplicationXFuturesplash,
		Gnumeric:    mime_type.ApplicationXGnumeric,
		Gtar:        mime_type.ApplicationXGtar,
		Hdf:         mime_type.ApplicationXHdf,
		Php:         mime_type.ApplicationXHttpdPhp,
		Jnlp:        mime_type.ApplicationXJavaJnlpFile,
		Latex:       mime_type.ApplicationXLatex,
		Prc:         mime_type.ApplicationXMobipocketEbook,
		Application: mime_type.ApplicationXMsApplication,
		Wmd:         mime_type.ApplicationXMsWmd,
		Wmz:         mime_type.ApplicationXMsWmz,
		Xbap:        mime_type.ApplicationXMsXbap,
		Mdb:         mime_type.ApplicationXMsaccess,
		Obd:         mime_type.ApplicationXMsbinder,
		Crd:         mime_type.ApplicationXMscardfile,
		Clp:         mime_type.ApplicationXMsclip,
		Exe:         mime_type.ApplicationXMsdownload,
		Mvb:         mime_type.ApplicationXMsmediaview,
		Wmf:         mime_type.ApplicationXMsmetafile,
		Mny:         mime_type.ApplicationXMsmoney,
		Pub:         mime_type.ApplicationXMspublisher,
		Scd:         mime_type.ApplicationXMsschedule,
		Trm:         mime_type.ApplicationXMsterminal,
		Wri:         mime_type.ApplicationXMswrite,
		Nc:          mime_type.ApplicationXNetcdf,
		P12:         mime_type.ApplicationXPkcs12,
		P7b:         mime_type.ApplicationXPkcs7Certificates,
		P7r:         mime_type.ApplicationXPkcs7Certreqresp,
		Sh:          mime_type.ApplicationXSh,
		Shar:        mime_type.ApplicationXShar,
		Swf:         mime_type.ApplicationXShockwaveFlash,
		Xap:         mime_type.ApplicationXSilverlightApp,
		Sit:         mime_type.ApplicationXStuffit,
		Sitx:        mime_type.ApplicationXStuffitx,
		Sv4cpio:     mime_type.ApplicationXSv4cpio,
		Sv4crc:      mime_type.ApplicationXSv4crc,
		Tar:         mime_type.ApplicationXTar,
		Tcl:         mime_type.ApplicationXTcl,
		Tex:         mime_type.ApplicationXTex,
		Tfm:         mime_type.ApplicationXTexTfm,
		Texinfo:     mime_type.ApplicationXTexinfo,
		Ustar:       mime_type.ApplicationXUstar,
		Src:         mime_type.ApplicationXWaisSource,
		Der:         mime_type.ApplicationXX509CaCert,
		Fig:         mime_type.ApplicationXXfig,
		Xpi:         mime_type.ApplicationXXpinstall,
		Yaml:        mime_type.ApplicationXYaml,
		Yml:         mime_type.ApplicationXYaml,
		Xdf:         mime_type.ApplicationXcapDiffXml,
		Xenc:        mime_type.ApplicationXencXml,
		Xhtml:       mime_type.ApplicationXhtmlXml,
		Xml:         mime_type.ApplicationXml,
		Dtd:         mime_type.ApplicationXmlDtd,
		Xop:         mime_type.ApplicationXopXml,
		Xslt:        mime_type.ApplicationXsltXml,
		Xspf:        mime_type.ApplicationXspfXml,
		Mxml:        mime_type.ApplicationXvXml,
		Yang:        mime_type.ApplicationYang,
		Yin:         mime_type.ApplicationYinXml,
		Zip:         mime_type.ApplicationZip,
		Adp:         mime_type.AudioAdpcm,
		Au:          mime_type.AudioBasic,
		Mid:         mime_type.AudioMidi,
		Midi:        mime_type.AudioMidi,
		Mp4a:        mime_type.AudioMp4,
		Mpga:        mime_type.AudioMpeg,
		Oga:         mime_type.AudioOgg,
		Opus:        mime_type.AudioOpus,
		Uva:         mime_type.AudioVndDeceAudio,
		Eol:         mime_type.AudioVndDigitalWinds,
		Dra:         mime_type.AudioVndDra,
		Dts:         mime_type.AudioVndDts,
		Dtshd:       mime_type.AudioVndDtsHd,
		Lvp:         mime_type.AudioVndLucentVoice,
		Pya:         mime_type.AudioVndMsPlayreadyMediaPya,
		Ecelp4800:   mime_type.AudioVndNueraEcelp4800,
		Ecelp7470:   mime_type.AudioVndNueraEcelp7470,
		Ecelp9600:   mime_type.AudioVndNueraEcelp9600,
		Rip:         mime_type.AudioVndRip,
		Wav:         mime_type.AudioWav,
		Weba:        mime_type.AudioWebm,
		Aac:         mime_type.AudioXAac,
		Aif:         mime_type.AudioXAiff,
		M3u:         mime_type.AudioXMpegurl,
		Wax:         mime_type.AudioXMsWax,
		Wma:         mime_type.AudioXMsWma,
		Ram:         mime_type.AudioXPnRealaudio,
		Rmp:         mime_type.AudioXPnRealaudioPlugin,
		Cdx:         mime_type.ChemicalXCdx,
		Cif:         mime_type.ChemicalXCif,
		Cmdf:        mime_type.ChemicalXCmdf,
		Cml:         mime_type.ChemicalXCml,
		Csml:        mime_type.ChemicalXCsml,
		Xyz:         mime_type.ChemicalXXyz,
		Otf:         mime_type.FontOtf,
		Ttf:         mime_type.FontTtf,
		Woff:        mime_type.FontWoff,
		Woff2:       mime_type.FontWoff2,
		Bmp:         mime_type.ImageBmp,
		Cgm:         mime_type.ImageCgm,
		G3:          mime_type.ImageG3fax,
		Gif:         mime_type.ImageGif,
		Ief:         mime_type.ImageIef,
		Jpeg:        mime_type.ImageJpeg,
		Jpg:         mime_type.ImageJpeg,
		Ktx:         mime_type.ImageKtx,
		Pjpeg:       mime_type.ImagePjpeg,
		Png:         mime_type.ImagePng,
		Btif:        mime_type.ImagePrsBtif,
		Svg:         mime_type.ImageSvgXml,
		Tif:         mime_type.ImageTiff,
		Tiff:        mime_type.ImageTiff,
		Psd:         mime_type.ImageVndAdobePhotoshop,
		Uvi:         mime_type.ImageVndDeceGraphic,
		Djvu:        mime_type.ImageVndDjvu,
		Sub:         mime_type.ImageVndDvbSubtitle,
		Dwg:         mime_type.ImageVndDwg,
		Dxf:         mime_type.ImageVndDxf,
		Fbs:         mime_type.ImageVndFastbidsheet,
		Fpx:         mime_type.ImageVndFpx,
		Fst:         mime_type.ImageVndFst,
		Mmr:         mime_type.ImageVndFujixeroxEdmicsMmr,
		Rlc:         mime_type.ImageVndFujixeroxEdmicsRlc,
		Mdi:         mime_type.ImageVndMsModi,
		Npx:         mime_type.ImageVndNetFpx,
		Wbmp:        mime_type.ImageVndWapWbmp,
		Xif:         mime_type.ImageVndXiff,
		Webp:        mime_type.ImageWebp,
		Ras:         mime_type.ImageXCmuRaster,
		Cmx:         mime_type.ImageXCmx,
		Fh:          mime_type.ImageXFreehand,
		Ico:         mime_type.ImageXIcon,
		Pcx:         mime_type.ImageXPcx,
		Pic:         mime_type.ImageXPict,
		Pnm:         mime_type.ImageXPortableAnymap,
		Pbm:         mime_type.ImageXPortableBitmap,
		Pgm:         mime_type.ImageXPortableGraymap,
		Ppm:         mime_type.ImageXPortablePixmap,
		Rgb:         mime_type.ImageXRgb,
		Xbm:         mime_type.ImageXXbitmap,
		Xpm:         mime_type.ImageXXpixmap,
		Xwd:         mime_type.ImageXXwindowdump,
		Eml:         mime_type.MessageRfc822,
		Igs:         mime_type.ModelIges,
		Msh:         mime_type.ModelMesh,
		Dae:         mime_type.ModelVndColladaXml,
		Dwf:         mime_type.ModelVndDwf,
		Gdl:         mime_type.ModelVndGdl,
		Gtw:         mime_type.ModelVndGtw,
		Mts:         mime_type.ModelVndMts,
		Vtu:         mime_type.ModelVndVtu,
		Wrl:         mime_type.ModelVrml,
		Ics:         mime_type.TextCalendar,
		Css:         mime_type.TextCss,
		Csv:         mime_type.TextCsv,
		Html:        mime_type.TextHtml,
		N3:          mime_type.TextN3,
		Txt:         mime_type.TextPlain,
		Par:         mime_type.TextPlainBas,
		Dsc:         mime_type.TextPrsLinesTag,
		Rtx:         mime_type.TextRichtext,
		Sgml:        mime_type.TextSgml,
		Tsv:         mime_type.TextTabSeparatedValues,
		T:           mime_type.TextTroff,
		Ttl:         mime_type.TextTurtle,
		Uri:         mime_type.TextUriList,
		Curl:        mime_type.TextVndCurl,
		Dcurl:       mime_type.TextVndCurlDcurl,
		Mcurl:       mime_type.TextVndCurlMcurl,
		Scurl:       mime_type.TextVndCurlScurl,
		Fly:         mime_type.TextVndFly,
		Flx:         mime_type.TextVndFmiFlexstor,
		Gv:          mime_type.TextVndGraphviz,
		_3dml:       mime_type.TextVndIn3d3dml,
		Spot:        mime_type.TextVndIn3dSpot,
		Jad:         mime_type.TextVndSunJ2meAppDescriptor,
		Wml:         mime_type.TextVndWapWml,
		Wmls:        mime_type.TextVndWapWmlscript,
		S:           mime_type.TextXAsm,
		C:           mime_type.TextXC,
		F:           mime_type.TextXFortran,
		Java:        mime_type.TextXJavaSource,
		P:           mime_type.TextXPascal,
		Etx:         mime_type.TextXSetext,
		Uu:          mime_type.TextXUuencode,
		Vcs:         mime_type.TextXVcalendar,
		Vcf:         mime_type.TextXVcard,
		_3gp:        mime_type.Video3gpp,
		_3g2:        mime_type.Video3gpp2,
		H261:        mime_type.VideoH261,
		H263:        mime_type.VideoH263,
		H264:        mime_type.VideoH264,
		Jpgv:        mime_type.VideoJpeg,
		Jpm:         mime_type.VideoJpm,
		Mj2:         mime_type.VideoMj2,
		Ts:          mime_type.VideoMp2t,
		Mp4:         mime_type.VideoMp4,
		Mpeg:        mime_type.VideoMpeg,
		Ogv:         mime_type.VideoOgg,
		Qt:          mime_type.VideoQuicktime,
		Uvh:         mime_type.VideoVndDeceHd,
		Uvm:         mime_type.VideoVndDeceMobile,
		Uvp:         mime_type.VideoVndDecePd,
		Uvs:         mime_type.VideoVndDeceSd,
		Uvv:         mime_type.VideoVndDeceVideo,
		Fvt:         mime_type.VideoVndFvt,
		Mxu:         mime_type.VideoVndMpegurl,
		Pyv:         mime_type.VideoVndMsPlayreadyMediaPyv,
		Uvu:         mime_type.VideoVndUvvuMp4,
		Viv:         mime_type.VideoVndVivo,
		Webm:        mime_type.VideoWebm,
		F4v:         mime_type.VideoXF4v,
		Fli:         mime_type.VideoXFli,
		Flv:         mime_type.VideoXFlv,
		M4v:         mime_type.VideoXM4v,
		Asf:         mime_type.VideoXMsAsf,
		Wm:          mime_type.VideoXMsWm,
		Wmv:         mime_type.VideoXMsWmv,
		Wmx:         mime_type.VideoXMsWmx,
		Wvx:         mime_type.VideoXMsWvx,
		Avi:         mime_type.VideoXMsvideo,
		Movie:       mime_type.VideoXSgiMovie,
		Ice:         mime_type.XConferenceXCooltalk,
		Toml:        mime_type.ApplicationToml,
		Hcl:         mime_type.ApplicationHcl,
		Ini:         mime_type.ApplicationIni,
	}

	mt2ext = map[mime_type.MimeType][]FileExtention{
		mime_type.ApplicationAndrewInset: {},
		mime_type.ApplicationApplixware: {
			Aw,
		},
		mime_type.ApplicationAtomXml: {
			Atom,
		},
		mime_type.ApplicationAtomcatXml: {
			Atomcat,
		},
		mime_type.ApplicationAtomsvcXml: {
			Atomsvc,
		},
		mime_type.ApplicationCcxmlXml: {
			Ccxml,
		},
		mime_type.ApplicationCdmiCapability: {
			Cdmia,
		},
		mime_type.ApplicationCdmiContainer: {
			Cdmic,
		},
		mime_type.ApplicationCdmiDomain: {
			Cdmid,
		},
		mime_type.ApplicationCdmiObject: {
			Cdmio,
		},
		mime_type.ApplicationCdmiQueue: {
			Cdmiq,
		},
		mime_type.ApplicationCuSeeme: {
			Cu,
		},
		mime_type.ApplicationDavmountXml: {
			Davmount,
		},
		mime_type.ApplicationDsscDer: {
			Dssc,
		},
		mime_type.ApplicationDsscXml: {
			Xdssc,
		},
		mime_type.ApplicationEcmascript: {
			Es,
		},
		mime_type.ApplicationEmmaXml: {
			Emma,
		},
		mime_type.ApplicationEpubZip: {
			Epub,
		},
		mime_type.ApplicationExi: {
			Exi,
		},
		mime_type.ApplicationFontTdpfr: {
			Pfr,
		},
		mime_type.ApplicationGpxXml: {
			Gpx,
		},
		mime_type.ApplicationGzip: {
			Gz,
		},
		mime_type.ApplicationHyperstudio: {
			Stk,
		},
		mime_type.ApplicationIpfix: {
			Ipfix,
		},
		mime_type.ApplicationJavaArchive: {
			Jar,
		},
		mime_type.ApplicationJavaSerializedObject: {
			Ser,
		},
		mime_type.ApplicationJavaVm: {
			Class,
		},
		mime_type.ApplicationJavascript: {
			Js,
		},
		mime_type.ApplicationJson: {
			Json,
		},
		mime_type.ApplicationLdJson: {
			Jsonld,
		},
		mime_type.ApplicationMacBinhex40: {
			Hqx,
		},
		mime_type.ApplicationMacCompactpro: {
			Cpt,
		},
		mime_type.ApplicationMadsXml: {
			Mads,
		},
		mime_type.ApplicationMarc: {
			Mrc,
		},
		mime_type.ApplicationMarcxmlXml: {
			Mrcx,
		},
		mime_type.ApplicationMathematica: {
			Ma,
		},
		mime_type.ApplicationMathmlXml: {
			Mathml,
		},
		mime_type.ApplicationMbox: {
			Mbox,
		},
		mime_type.ApplicationMediaservercontrolXml: {
			Mscml,
		},
		mime_type.ApplicationMetalink4Xml: {
			Meta4,
		},
		mime_type.ApplicationMetsXml: {
			Mets,
		},
		mime_type.ApplicationModsXml: {
			Mods,
		},
		mime_type.ApplicationMp21: {
			M21,
		},
		mime_type.ApplicationMsword: {
			Doc,
		},
		mime_type.ApplicationMxf: {
			Mxf,
		},
		mime_type.ApplicationOctetStream: {
			Bin,
		},
		mime_type.ApplicationOda: {
			Oda,
		},
		mime_type.ApplicationOebpsPackageXml: {
			Opf,
		},
		mime_type.ApplicationOgg: {
			Ogx,
		},
		mime_type.ApplicationOnenote: {
			Onetoc,
		},
		mime_type.ApplicationPatchOpsErrorXml: {
			Xer,
		},
		mime_type.ApplicationPdf: {
			Pdf,
		},
		mime_type.ApplicationPgpEncrypted: {
			Pgp,
		},
		mime_type.ApplicationPicsRules: {
			Prf,
		},
		mime_type.ApplicationPkcs10: {
			P10,
		},
		mime_type.ApplicationPkcs7Mime: {
			P7m,
		},
		mime_type.ApplicationPkcs7Signature: {
			P7s,
		},
		mime_type.ApplicationPkcs8: {
			P8,
		},
		mime_type.ApplicationPkixAttrCert: {
			Ac,
		},
		mime_type.ApplicationPkixCert: {
			Cer,
		},
		mime_type.ApplicationPkixCrl: {
			Crl,
		},
		mime_type.ApplicationPkixPkipath: {
			Pkipath,
		},
		mime_type.ApplicationPkixcmp: {
			Pki,
		},
		mime_type.ApplicationPlsXml: {
			Pls,
		},
		mime_type.ApplicationPostscript: {
			Ai,
		},
		mime_type.ApplicationPrsCww: {
			Cww,
		},
		mime_type.ApplicationPskcXml: {
			Pskcxml,
		},
		mime_type.ApplicationRdfXml: {
			Rdf,
		},
		mime_type.ApplicationReginfoXml: {
			Rif,
		},
		mime_type.ApplicationRelaxNgCompactSyntax: {
			Rnc,
		},
		mime_type.ApplicationResourceListsXml: {
			Rl,
		},
		mime_type.ApplicationResourceListsDiffXml: {
			Rld,
		},
		mime_type.ApplicationRlsServicesXml: {
			Rs,
		},
		mime_type.ApplicationRsdXml: {
			Rsd,
		},
		mime_type.ApplicationRssXml: {
			Rss,
		},
		mime_type.ApplicationRtf: {
			Rtf,
		},
		mime_type.ApplicationSbmlXml: {
			Sbml,
		},
		mime_type.ApplicationScvpCvRequest: {
			Scq,
		},
		mime_type.ApplicationScvpCvResponse: {
			Scs,
		},
		mime_type.ApplicationScvpVpRequest: {
			Spq,
		},
		mime_type.ApplicationScvpVpResponse: {
			Spp,
		},
		mime_type.ApplicationSdp: {
			Sdp,
		},
		mime_type.ApplicationSetPaymentInitiation: {
			Setpay,
		},
		mime_type.ApplicationSetRegistrationInitiation: {
			Setreg,
		},
		mime_type.ApplicationShfXml: {
			Shf,
		},
		mime_type.ApplicationSmilXml: {
			Smi,
		},
		mime_type.ApplicationSparqlQuery: {
			Rq,
		},
		mime_type.ApplicationSparqlResultsXml: {
			Srx,
		},
		mime_type.ApplicationSrgs: {
			Gram,
		},
		mime_type.ApplicationSrgsXml: {
			Grxml,
		},
		mime_type.ApplicationSruXml: {
			Sru,
		},
		mime_type.ApplicationSsmlXml: {
			Ssml,
		},
		mime_type.ApplicationTeiXml: {
			Tei,
		},
		mime_type.ApplicationThraudXml: {
			Tfi,
		},
		mime_type.ApplicationTimestampedData: {
			Tsd,
		},
		mime_type.ApplicationVnd3gppPicBwLarge: {
			Plb,
		},
		mime_type.ApplicationVnd3gppPicBwSmall: {
			Psb,
		},
		mime_type.ApplicationVnd3gppPicBwVar: {
			Pvb,
		},
		mime_type.ApplicationVnd3gpp2Tcap: {
			Tcap,
		},
		mime_type.ApplicationVnd3mPostItNotes: {
			Pwn,
		},
		mime_type.ApplicationVndAccpacSimplyAso: {
			Aso,
		},
		mime_type.ApplicationVndAccpacSimplyImp: {
			Imp,
		},
		mime_type.ApplicationVndAcucobol: {
			Acu,
		},
		mime_type.ApplicationVndAcucorp: {
			Atc,
		},
		mime_type.ApplicationVndAdobeAirApplicationInstallerPackageZip: {
			Air,
		},
		mime_type.ApplicationVndAdobeFxp: {
			Fxp,
		},
		mime_type.ApplicationVndAdobeXdpXml: {
			Xdp,
		},
		mime_type.ApplicationVndAdobeXfdf: {
			Xfdf,
		},
		mime_type.ApplicationVndAheadSpace: {
			Ahead,
		},
		mime_type.ApplicationVndAirzipFilesecureAzf: {
			Azf,
		},
		mime_type.ApplicationVndAirzipFilesecureAzs: {
			Azs,
		},
		mime_type.ApplicationVndAmazonEbook: {
			Azw,
		},
		mime_type.ApplicationVndAmericandynamicsAcc: {
			Acc,
		},
		mime_type.ApplicationVndAmigaAmi: {
			Ami,
		},
		mime_type.ApplicationVndAndroidPackageArchive: {
			Apk,
		},
		mime_type.ApplicationVndAnserWebCertificateIssueInitiation: {
			Cii,
		},
		mime_type.ApplicationVndAnserWebFundsTransferInitiation: {
			Fti,
		},
		mime_type.ApplicationVndAntixGameComponent: {
			Atx,
		},
		mime_type.ApplicationVndAppleInstallerXml: {
			Mpkg,
		},
		mime_type.ApplicationVndAppleMpegurl: {
			M3u8,
		},
		mime_type.ApplicationVndAristanetworksSwi: {
			Swi,
		},
		mime_type.ApplicationVndAudiograph: {
			Aep,
		},
		mime_type.ApplicationVndBlueiceMultipass: {
			Mpm,
		},
		mime_type.ApplicationVndBmi: {
			Bmi,
		},
		mime_type.ApplicationVndBusinessobjects: {
			Rep,
		},
		mime_type.ApplicationVndChemdrawXml: {
			Cdxml,
		},
		mime_type.ApplicationVndChipnutsKaraokeMmd: {
			Mmd,
		},
		mime_type.ApplicationVndCinderella: {
			Cdy,
		},
		mime_type.ApplicationVndClaymore: {
			Cla,
		},
		mime_type.ApplicationVndCloantoRp9: {
			Rp9,
		},
		mime_type.ApplicationVndClonkC4group: {
			C4g,
		},
		mime_type.ApplicationVndCluetrustCartomobileConfig: {
			C11amc,
		},
		mime_type.ApplicationVndCluetrustCartomobileConfigPkg: {
			C11amz,
		},
		mime_type.ApplicationVndCommonspace: {
			Csp,
		},
		mime_type.ApplicationVndContactCmsg: {
			Cdbcmsg,
		},
		mime_type.ApplicationVndCosmocaller: {
			Cmc,
		},
		mime_type.ApplicationVndCrickClicker: {
			Clkx,
		},
		mime_type.ApplicationVndCrickClickerKeyboard: {
			Clkk,
		},
		mime_type.ApplicationVndCrickClickerPalette: {
			Clkp,
		},
		mime_type.ApplicationVndCrickClickerTemplate: {
			Clkt,
		},
		mime_type.ApplicationVndCrickClickerWordbank: {
			Clkw,
		},
		mime_type.ApplicationVndCriticaltoolsWbsXml: {
			Wbs,
		},
		mime_type.ApplicationVndCtcPosml: {
			Pml,
		},
		mime_type.ApplicationVndCupsPpd: {
			Ppd,
		},
		mime_type.ApplicationVndCurlCar: {
			Car,
		},
		mime_type.ApplicationVndCurlPcurl: {
			Pcurl,
		},
		mime_type.ApplicationVndDataVisionRdz: {
			Rdz,
		},
		mime_type.ApplicationVndDenovoFcselayoutLink: {
			Fe_launch,
		},
		mime_type.ApplicationVndDna: {
			Dna,
		},
		mime_type.ApplicationVndDolbyMlp: {
			Mlp,
		},
		mime_type.ApplicationVndDpgraph: {
			Dpg,
		},
		mime_type.ApplicationVndDreamfactory: {
			Dfac,
		},
		mime_type.ApplicationVndDvbAit: {
			Ait,
		},
		mime_type.ApplicationVndDvbService: {
			Svc,
		},
		mime_type.ApplicationVndDynageo: {
			Geo,
		},
		mime_type.ApplicationVndEcowinChart: {
			Mag,
		},
		mime_type.ApplicationVndEnliven: {
			Nml,
		},
		mime_type.ApplicationVndEpsonEsf: {
			Esf,
		},
		mime_type.ApplicationVndEpsonMsf: {
			Msf,
		},
		mime_type.ApplicationVndEpsonQuickanime: {
			Qam,
		},
		mime_type.ApplicationVndEpsonSalt: {
			Slt,
		},
		mime_type.ApplicationVndEpsonSsf: {
			Ssf,
		},
		mime_type.ApplicationVndEszigno3Xml: {
			Es3,
		},
		mime_type.ApplicationVndEzpixAlbum: {
			Ez2,
		},
		mime_type.ApplicationVndEzpixPackage: {
			Ez3,
		},
		mime_type.ApplicationVndFdf: {
			Fdf,
		},
		mime_type.ApplicationVndFdsnSeed: {
			Seed,
		},
		mime_type.ApplicationVndFlographit: {
			Gph,
		},
		mime_type.ApplicationVndFluxtimeClip: {
			Ftc,
		},
		mime_type.ApplicationVndFramemaker: {
			Fm,
		},
		mime_type.ApplicationVndFrogansFnc: {
			Fnc,
		},
		mime_type.ApplicationVndFrogansLtf: {
			Ltf,
		},
		mime_type.ApplicationVndFscWeblaunch: {
			Fsc,
		},
		mime_type.ApplicationVndFujitsuOasys: {
			Oas,
		},
		mime_type.ApplicationVndFujitsuOasys2: {
			Oa2,
		},
		mime_type.ApplicationVndFujitsuOasys3: {
			Oa3,
		},
		mime_type.ApplicationVndFujitsuOasysgp: {
			Fg5,
		},
		mime_type.ApplicationVndFujitsuOasysprs: {
			Bh2,
		},
		mime_type.ApplicationVndFujixeroxDdd: {
			Ddd,
		},
		mime_type.ApplicationVndFujixeroxDocuworks: {
			Xdw,
		},
		mime_type.ApplicationVndFujixeroxDocuworksBinder: {
			Xbd,
		},
		mime_type.ApplicationVndFuzzysheet: {
			Fzs,
		},
		mime_type.ApplicationVndGenomatixTuxedo: {
			Txd,
		},
		mime_type.ApplicationVndGeogebraFile: {
			Ggb,
		},
		mime_type.ApplicationVndGeogebraTool: {
			Ggt,
		},
		mime_type.ApplicationVndGeometryExplorer: {
			Gex,
		},
		mime_type.ApplicationVndGeonext: {
			Gxt,
		},
		mime_type.ApplicationVndGeoplan: {
			G2w,
		},
		mime_type.ApplicationVndGeospace: {
			G3w,
		},
		mime_type.ApplicationVndGmx: {
			Gmx,
		},
		mime_type.ApplicationVndGoogleEarthKmlXml: {
			Kml,
		},
		mime_type.ApplicationVndGoogleEarthKmz: {
			Kmz,
		},
		mime_type.ApplicationVndGrafeq: {
			Gqf,
		},
		mime_type.ApplicationVndGrooveAccount: {
			Gac,
		},
		mime_type.ApplicationVndGrooveHelp: {
			Ghf,
		},
		mime_type.ApplicationVndGrooveIdentityMessage: {
			Gim,
		},
		mime_type.ApplicationVndGrooveInjector: {
			Grv,
		},
		mime_type.ApplicationVndGrooveToolMessage: {
			Gtm,
		},
		mime_type.ApplicationVndGrooveToolTemplate: {
			Tpl,
		},
		mime_type.ApplicationVndGrooveVcard: {
			Vcg,
		},
		mime_type.ApplicationVndHalXml: {
			Hal,
		},
		mime_type.ApplicationVndHandheldEntertainmentXml: {
			Zmm,
		},
		mime_type.ApplicationVndHbci: {
			Hbci,
		},
		mime_type.ApplicationVndHheLessonPlayer: {
			Les,
		},
		mime_type.ApplicationVndHpHpgl: {
			Hpgl,
		},
		mime_type.ApplicationVndHpHpid: {
			Hpid,
		},
		mime_type.ApplicationVndHpHps: {
			Hps,
		},
		mime_type.ApplicationVndHpJlyt: {
			Jlt,
		},
		mime_type.ApplicationVndHpPcl: {
			Pcl,
		},
		mime_type.ApplicationVndHpPclxl: {
			Pclxl,
		},
		mime_type.ApplicationVndHydrostatixSofData: {
			SfdHdstx,
		},
		mime_type.ApplicationVndHzn3dCrossword: {
			X3d,
		},
		mime_type.ApplicationVndIbmMinipay: {
			Mpy,
		},
		mime_type.ApplicationVndIbmModcap: {
			Afp,
		},
		mime_type.ApplicationVndIbmRightsManagement: {
			Irm,
		},
		mime_type.ApplicationVndIbmSecureContainer: {
			Sc,
		},
		mime_type.ApplicationVndIccprofile: {
			Icc,
		},
		mime_type.ApplicationVndIgloader: {
			Igl,
		},
		mime_type.ApplicationVndImmervisionIvp: {
			Ivp,
		},
		mime_type.ApplicationVndImmervisionIvu: {
			Ivu,
		},
		mime_type.ApplicationVndInsorsIgm: {
			Igm,
		},
		mime_type.ApplicationVndInterconFormnet: {
			Xpw,
		},
		mime_type.ApplicationVndIntergeo: {
			I2g,
		},
		mime_type.ApplicationVndIntuQbo: {
			Qbo,
		},
		mime_type.ApplicationVndIntuQfx: {
			Qfx,
		},
		mime_type.ApplicationVndIpunpluggedRcprofile: {
			Rcprofile,
		},
		mime_type.ApplicationVndIrepositoryPackageXml: {
			Irp,
		},
		mime_type.ApplicationVndIsXpr: {
			Xpr,
		},
		mime_type.ApplicationVndIsacFcs: {
			Fcs,
		},
		mime_type.ApplicationVndJam: {
			Jam,
		},
		mime_type.ApplicationVndJcpJavameMidletRms: {
			Rms,
		},
		mime_type.ApplicationVndJisp: {
			Jisp,
		},
		mime_type.ApplicationVndJoostJodaArchive: {
			Joda,
		},
		mime_type.ApplicationVndKahootz: {
			Ktz,
		},
		mime_type.ApplicationVndKdeKarbon: {
			Karbon,
		},
		mime_type.ApplicationVndKdeKchart: {
			Chrt,
		},
		mime_type.ApplicationVndKdeKformula: {
			Kfo,
		},
		mime_type.ApplicationVndKdeKivio: {
			Flw,
		},
		mime_type.ApplicationVndKdeKontour: {
			Kon,
		},
		mime_type.ApplicationVndKdeKpresenter: {
			Kpr,
		},
		mime_type.ApplicationVndKdeKspread: {
			Ksp,
		},
		mime_type.ApplicationVndKdeKword: {
			Kwd,
		},
		mime_type.ApplicationVndKenameaapp: {
			Htke,
		},
		mime_type.ApplicationVndKidspiration: {
			Kia,
		},
		mime_type.ApplicationVndKinar: {
			Kne,
		},
		mime_type.ApplicationVndKoan: {
			Skp,
		},
		mime_type.ApplicationVndKodakDescriptor: {
			Sse,
		},
		mime_type.ApplicationVndLasLasXml: {
			Lasxml,
		},
		mime_type.ApplicationVndLlamagraphicsLifeBalanceDesktop: {
			Lbd,
		},
		mime_type.ApplicationVndLlamagraphicsLifeBalanceExchangeXml: {
			Lbe,
		},
		mime_type.ApplicationVndLotus123: {
			_123,
		},
		mime_type.ApplicationVndLotusApproach: {
			Apr,
		},
		mime_type.ApplicationVndLotusFreelance: {
			Pre,
		},
		mime_type.ApplicationVndLotusNotes: {
			Nsf,
		},
		mime_type.ApplicationVndLotusOrganizer: {
			Org,
		},
		mime_type.ApplicationVndLotusScreencam: {
			Scm,
		},
		mime_type.ApplicationVndLotusWordpro: {
			Lwp,
		},
		mime_type.ApplicationVndMacportsPortpkg: {
			Portpkg,
		},
		mime_type.ApplicationVndMcd: {
			Mcd,
		},
		mime_type.ApplicationVndMedcalcdata: {
			Mc1,
		},
		mime_type.ApplicationVndMediastationCdkey: {
			Cdkey,
		},
		mime_type.ApplicationVndMfer: {
			Mwf,
		},
		mime_type.ApplicationVndMfmp: {
			Mfm,
		},
		mime_type.ApplicationVndMicrografxFlo: {
			Flo,
		},
		mime_type.ApplicationVndMicrografxIgx: {
			Igx,
		},
		mime_type.ApplicationVndMif: {
			Mif,
		},
		mime_type.ApplicationVndMobiusDaf: {
			Daf,
		},
		mime_type.ApplicationVndMobiusDis: {
			Dis,
		},
		mime_type.ApplicationVndMobiusMbk: {
			Mbk,
		},
		mime_type.ApplicationVndMobiusMqy: {
			Mqy,
		},
		mime_type.ApplicationVndMobiusMsl: {
			Msl,
		},
		mime_type.ApplicationVndMobiusPlc: {
			Plc,
		},
		mime_type.ApplicationVndMobiusTxf: {
			Txf,
		},
		mime_type.ApplicationVndMophunApplication: {
			Mpn,
		},
		mime_type.ApplicationVndMophunCertificate: {
			Mpc,
		},
		mime_type.ApplicationVndMozillaXulXml: {
			Xul,
		},
		mime_type.ApplicationVndMsArtgalry: {
			Cil,
		},
		mime_type.ApplicationVndMsCabCompressed: {
			Cab,
		},
		mime_type.ApplicationVndMsExcel: {
			Xls,
		},
		mime_type.ApplicationVndMsExcelAddinMacroenabled12: {
			Xlam,
		},
		mime_type.ApplicationVndMsExcelSheetBinaryMacroenabled12: {
			Xlsb,
		},
		mime_type.ApplicationVndMsExcelSheetMacroenabled12: {
			Xlsm,
		},
		mime_type.ApplicationVndMsExcelTemplateMacroenabled12: {
			Xltm,
		},
		mime_type.ApplicationVndMsFontobject: {
			Eot,
		},
		mime_type.ApplicationVndMsHtmlhelp: {
			Chm,
		},
		mime_type.ApplicationVndMsIms: {
			Ims,
		},
		mime_type.ApplicationVndMsLrm: {
			Lrm,
		},
		mime_type.ApplicationVndMsOfficetheme: {
			Thmx,
		},
		mime_type.ApplicationVndMsPkiSeccat: {
			Cat,
		},
		mime_type.ApplicationVndMsPkiStl: {
			Stl,
		},
		mime_type.ApplicationVndMsPowerpoint: {
			Ppt,
		},
		mime_type.ApplicationVndMsPowerpointAddinMacroenabled12: {
			Ppam,
		},
		mime_type.ApplicationVndMsPowerpointPresentationMacroenabled12: {
			Pptm,
		},
		mime_type.ApplicationVndMsPowerpointSlideMacroenabled12: {
			Sldm,
		},
		mime_type.ApplicationVndMsPowerpointSlideshowMacroenabled12: {
			Ppsm,
		},
		mime_type.ApplicationVndMsPowerpointTemplateMacroenabled12: {
			Potm,
		},
		mime_type.ApplicationVndMsProject: {
			Mpp,
		},
		mime_type.ApplicationVndMsWordDocumentMacroenabled12: {
			Docm,
		},
		mime_type.ApplicationVndMsWordTemplateMacroenabled12: {
			Dotm,
		},
		mime_type.ApplicationVndMsWorks: {
			Wps,
		},
		mime_type.ApplicationVndMsWpl: {
			Wpl,
		},
		mime_type.ApplicationVndMsXpsdocument: {
			Xps,
		},
		mime_type.ApplicationVndMseq: {
			Mseq,
		},
		mime_type.ApplicationVndMusician: {
			Mus,
		},
		mime_type.ApplicationVndMuveeStyle: {
			Msty,
		},
		mime_type.ApplicationVndNeurolanguageNlu: {
			Nlu,
		},
		mime_type.ApplicationVndNoblenetDirectory: {
			Nnd,
		},
		mime_type.ApplicationVndNoblenetSealer: {
			Nns,
		},
		mime_type.ApplicationVndNoblenetWeb: {
			Nnw,
		},
		mime_type.ApplicationVndNokiaNGageData: {
			Ngdat,
		},
		mime_type.ApplicationVndNokiaNGageSymbianInstall: {
			NGage,
		},
		mime_type.ApplicationVndNokiaRadioPreset: {
			Rpst,
		},
		mime_type.ApplicationVndNokiaRadioPresets: {
			Rpss,
		},
		mime_type.ApplicationVndNovadigmEdm: {
			Edm,
		},
		mime_type.ApplicationVndNovadigmEdx: {
			Edx,
		},
		mime_type.ApplicationVndNovadigmExt: {
			Ext,
		},
		mime_type.ApplicationVndOasisOpendocumentChart: {
			Odc,
		},
		mime_type.ApplicationVndOasisOpendocumentChartTemplate: {
			Otc,
		},
		mime_type.ApplicationVndOasisOpendocumentDatabase: {
			Odb,
		},
		mime_type.ApplicationVndOasisOpendocumentFormula: {
			Odf,
		},
		mime_type.ApplicationVndOasisOpendocumentFormulaTemplate: {
			Odft,
		},
		mime_type.ApplicationVndOasisOpendocumentGraphics: {
			Odg,
		},
		mime_type.ApplicationVndOasisOpendocumentGraphicsTemplate: {
			Otg,
		},
		mime_type.ApplicationVndOasisOpendocumentImage: {
			Odi,
		},
		mime_type.ApplicationVndOasisOpendocumentImageTemplate: {
			Oti,
		},
		mime_type.ApplicationVndOasisOpendocumentPresentation: {
			Odp,
		},
		mime_type.ApplicationVndOasisOpendocumentPresentationTemplate: {
			Otp,
		},
		mime_type.ApplicationVndOasisOpendocumentSpreadsheet: {
			Ods,
		},
		mime_type.ApplicationVndOasisOpendocumentSpreadsheetTemplate: {
			Ots,
		},
		mime_type.ApplicationVndOasisOpendocumentText: {
			Odt,
		},
		mime_type.ApplicationVndOasisOpendocumentTextMaster: {
			Odm,
		},
		mime_type.ApplicationVndOasisOpendocumentTextTemplate: {
			Ott,
		},
		mime_type.ApplicationVndOasisOpendocumentTextWeb: {
			Oth,
		},
		mime_type.ApplicationVndOlpcSugar: {
			Xo,
		},
		mime_type.ApplicationVndOmaDd2Xml: {
			Dd2,
		},
		mime_type.ApplicationVndOpenofficeorgExtension: {
			Oxt,
		},
		mime_type.ApplicationVndOpenxmlformatsOfficedocumentPresentationmlPresentation: {
			Pptx,
		},
		mime_type.ApplicationVndOpenxmlformatsOfficedocumentPresentationmlSlide: {
			Sldx,
		},
		mime_type.ApplicationVndOpenxmlformatsOfficedocumentPresentationmlSlideshow: {
			Ppsx,
		},
		mime_type.ApplicationVndOpenxmlformatsOfficedocumentPresentationmlTemplate: {
			Potx,
		},
		mime_type.ApplicationVndOpenxmlformatsOfficedocumentSpreadsheetmlSheet: {
			Xlsx,
		},
		mime_type.ApplicationVndOpenxmlformatsOfficedocumentSpreadsheetmlTemplate: {
			Xltx,
		},
		mime_type.ApplicationVndOpenxmlformatsOfficedocumentWordprocessingmlDocument: {
			Docx,
		},
		mime_type.ApplicationVndOpenxmlformatsOfficedocumentWordprocessingmlTemplate: {
			Dotx,
		},
		mime_type.ApplicationVndOsgeoMapguidePackage: {
			Mgp,
		},
		mime_type.ApplicationVndOsgiDp: {
			Dp,
		},
		mime_type.ApplicationVndPalm: {
			Pdb,
		},
		mime_type.ApplicationVndPawaafile: {
			Paw,
		},
		mime_type.ApplicationVndPgFormat: {
			Str,
		},
		mime_type.ApplicationVndPgOsasli: {
			Ei6,
		},
		mime_type.ApplicationVndPicsel: {
			Efif,
		},
		mime_type.ApplicationVndPmiWidget: {
			Wg,
		},
		mime_type.ApplicationVndPocketlearn: {
			Plf,
		},
		mime_type.ApplicationVndPowerbuilder6: {
			Pbd,
		},
		mime_type.ApplicationVndPreviewsystemsBox: {
			Box,
		},
		mime_type.ApplicationVndProteusMagazine: {
			Mgz,
		},
		mime_type.ApplicationVndPublishareDeltaTree: {
			Qps,
		},
		mime_type.ApplicationVndPviPtid1: {
			Ptid,
		},
		mime_type.ApplicationVndQuarkQuarkxpress: {
			Qxd,
		},
		mime_type.ApplicationVndRar: {
			Rar,
		},
		mime_type.ApplicationVndRealvncBed: {
			Bed,
		},
		mime_type.ApplicationVndRecordareMusicxml: {
			Mxl,
		},
		mime_type.ApplicationVndRecordareMusicxmlXml: {
			Musicxml,
		},
		mime_type.ApplicationVndRigCryptonote: {
			Cryptonote,
		},
		mime_type.ApplicationVndRimCod: {
			Cod,
		},
		mime_type.ApplicationVndRnRealmedia: {
			Rm,
		},
		mime_type.ApplicationVndRoute66Link66Xml: {
			Link66,
		},
		mime_type.ApplicationVndSailingtrackerTrack: {
			St,
		},
		mime_type.ApplicationVndSeemail: {
			See,
		},
		mime_type.ApplicationVndSema: {
			Sema,
		},
		mime_type.ApplicationVndSemd: {
			Semd,
		},
		mime_type.ApplicationVndSemf: {
			Semf,
		},
		mime_type.ApplicationVndShanaInformedFormdata: {
			Ifm,
		},
		mime_type.ApplicationVndShanaInformedFormtemplate: {
			Itp,
		},
		mime_type.ApplicationVndShanaInformedInterchange: {
			Iif,
		},
		mime_type.ApplicationVndShanaInformedPackage: {
			Ipk,
		},
		mime_type.ApplicationVndSimtechMindmapper: {
			Twd,
		},
		mime_type.ApplicationVndSmaf: {
			Mmf,
		},
		mime_type.ApplicationVndSmartTeacher: {
			Teacher,
		},
		mime_type.ApplicationVndSolentSdkmXml: {
			Sdkm,
		},
		mime_type.ApplicationVndSpotfireDxp: {
			Dxp,
		},
		mime_type.ApplicationVndSpotfireSfs: {
			Sfs,
		},
		mime_type.ApplicationVndStardivisionCalc: {
			Sdc,
		},
		mime_type.ApplicationVndStardivisionDraw: {
			Sda,
		},
		mime_type.ApplicationVndStardivisionImpress: {
			Sdd,
		},
		mime_type.ApplicationVndStardivisionMath: {
			Smf,
		},
		mime_type.ApplicationVndStardivisionWriter: {
			Sdw,
		},
		mime_type.ApplicationVndStardivisionWriterGlobal: {
			Sgl,
		},
		mime_type.ApplicationVndStepmaniaStepchart: {
			Sm,
		},
		mime_type.ApplicationVndSunXmlCalc: {
			Sxc,
		},
		mime_type.ApplicationVndSunXmlCalcTemplate: {
			Stc,
		},
		mime_type.ApplicationVndSunXmlDraw: {
			Sxd,
		},
		mime_type.ApplicationVndSunXmlDrawTemplate: {
			Std,
		},
		mime_type.ApplicationVndSunXmlImpress: {
			Sxi,
		},
		mime_type.ApplicationVndSunXmlImpressTemplate: {
			Sti,
		},
		mime_type.ApplicationVndSunXmlMath: {
			Sxm,
		},
		mime_type.ApplicationVndSunXmlWriter: {
			Sxw,
		},
		mime_type.ApplicationVndSunXmlWriterGlobal: {
			Sxg,
		},
		mime_type.ApplicationVndSunXmlWriterTemplate: {
			Stw,
		},
		mime_type.ApplicationVndSusCalendar: {
			Sus,
		},
		mime_type.ApplicationVndSvd: {
			Svd,
		},
		mime_type.ApplicationVndSymbianInstall: {
			Sis,
		},
		mime_type.ApplicationVndSyncmlXml: {
			Xsm,
		},
		mime_type.ApplicationVndSyncmlDmWbxml: {
			Bdm,
		},
		mime_type.ApplicationVndSyncmlDmXml: {
			Xdm,
		},
		mime_type.ApplicationVndTaoIntentModuleArchive: {
			Tao,
		},
		mime_type.ApplicationVndTmobileLivetv: {
			Tmo,
		},
		mime_type.ApplicationVndTridTpt: {
			Tpt,
		},
		mime_type.ApplicationVndTriscapeMxs: {
			Mxs,
		},
		mime_type.ApplicationVndTrueapp: {
			Tra,
		},
		mime_type.ApplicationVndUfdl: {
			Ufd,
		},
		mime_type.ApplicationVndUiqTheme: {
			Utz,
		},
		mime_type.ApplicationVndUmajin: {
			Umj,
		},
		mime_type.ApplicationVndUnity: {
			Unityweb,
		},
		mime_type.ApplicationVndUomlXml: {
			Uoml,
		},
		mime_type.ApplicationVndVcx: {
			Vcx,
		},
		mime_type.ApplicationVndVisio: {
			Vsd,
		},
		mime_type.ApplicationVndVisio2013: {
			Vsdx,
		},
		mime_type.ApplicationVndVisionary: {
			Vis,
		},
		mime_type.ApplicationVndVsf: {
			Vsf,
		},
		mime_type.ApplicationVndWapWbxml: {
			Wbxml,
		},
		mime_type.ApplicationVndWapWmlc: {
			Wmlc,
		},
		mime_type.ApplicationVndWapWmlscriptc: {
			Wmlsc,
		},
		mime_type.ApplicationVndWebturbo: {
			Wtb,
		},
		mime_type.ApplicationVndWolframPlayer: {
			Nbp,
		},
		mime_type.ApplicationVndWordperfect: {
			Wpd,
		},
		mime_type.ApplicationVndWqd: {
			Wqd,
		},
		mime_type.ApplicationVndWtStf: {
			Stf,
		},
		mime_type.ApplicationVndXara: {
			Xar,
		},
		mime_type.ApplicationVndXfdl: {
			Xfdl,
		},
		mime_type.ApplicationVndYamahaHvDic: {
			Hvd,
		},
		mime_type.ApplicationVndYamahaHvScript: {
			Hvs,
		},
		mime_type.ApplicationVndYamahaHvVoice: {
			Hvp,
		},
		mime_type.ApplicationVndYamahaOpenscoreformat: {
			Osf,
		},
		mime_type.ApplicationVndYamahaOpenscoreformatOsfpvgXml: {
			Osfpvg,
		},
		mime_type.ApplicationVndYamahaSmafAudio: {
			Saf,
		},
		mime_type.ApplicationVndYamahaSmafPhrase: {
			Spf,
		},
		mime_type.ApplicationVndYellowriverCustomMenu: {
			Cmp,
		},
		mime_type.ApplicationVndZul: {
			Zir,
		},
		mime_type.ApplicationVndZzazzDeckXml: {
			Zaz,
		},
		mime_type.ApplicationVoicexmlXml: {
			Vxml,
		},
		mime_type.ApplicationWidget: {
			Wgt,
		},
		mime_type.ApplicationWinhlp: {
			Hlp,
		},
		mime_type.ApplicationWsdlXml: {
			Wsdl,
		},
		mime_type.ApplicationWspolicyXml: {
			Wspolicy,
		},
		mime_type.ApplicationX7zCompressed: {
			_7z,
		},
		mime_type.ApplicationXAbiword: {
			Abw,
		},
		mime_type.ApplicationXAceCompressed: {
			Ace,
		},
		mime_type.ApplicationXAppleDiskimage: {
			Dmg,
		},
		mime_type.ApplicationXAuthorwareBin: {
			Aab,
		},
		mime_type.ApplicationXAuthorwareMap: {
			Aam,
		},
		mime_type.ApplicationXAuthorwareSeg: {
			Aas,
		},
		mime_type.ApplicationXBcpio: {
			Bcpio,
		},
		mime_type.ApplicationXBittorrent: {
			Torrent,
		},
		mime_type.ApplicationXBzip: {
			Bz,
		},
		mime_type.ApplicationXBzip2: {
			Bz2,
		},
		mime_type.ApplicationXCdf: {
			Cda,
		},
		mime_type.ApplicationXCdlink: {
			Vcd,
		},
		mime_type.ApplicationXChat: {
			Chat,
		},
		mime_type.ApplicationXChessPgn: {
			Pgn,
		},
		mime_type.ApplicationXCpio: {
			Cpio,
		},
		mime_type.ApplicationXCsh: {
			Csh,
		},
		mime_type.ApplicationXDebianPackage: {
			Deb,
		},
		mime_type.ApplicationXDirector: {
			Dir,
		},
		mime_type.ApplicationXDoom: {
			Wad,
		},
		mime_type.ApplicationXDtbncxXml: {
			Ncx,
		},
		mime_type.ApplicationXDtbookXml: {
			Dtb,
		},
		mime_type.ApplicationXDtbresourceXml: {
			Res,
		},
		mime_type.ApplicationXDvi: {
			Dvi,
		},
		mime_type.ApplicationXFontBdf: {
			Bdf,
		},
		mime_type.ApplicationXFontGhostscript: {
			Gsf,
		},
		mime_type.ApplicationXFontLinuxPsf: {
			Psf,
		},
		mime_type.ApplicationXFontPcf: {
			Pcf,
		},
		mime_type.ApplicationXFontSnf: {
			Snf,
		},
		mime_type.ApplicationXFontType1: {
			Pfa,
		},
		mime_type.ApplicationXFreearc: {
			Arc,
		},
		mime_type.ApplicationXFuturesplash: {
			Spl,
		},
		mime_type.ApplicationXGnumeric: {
			Gnumeric,
		},
		mime_type.ApplicationXGtar: {
			Gtar,
		},
		mime_type.ApplicationXHdf: {
			Hdf,
		},
		mime_type.ApplicationXHttpdPhp: {
			Php,
		},
		mime_type.ApplicationXJavaJnlpFile: {
			Jnlp,
		},
		mime_type.ApplicationXLatex: {
			Latex,
		},
		mime_type.ApplicationXMobipocketEbook: {
			Prc,
		},
		mime_type.ApplicationXMsApplication: {
			Application,
		},
		mime_type.ApplicationXMsWmd: {
			Wmd,
		},
		mime_type.ApplicationXMsWmz: {
			Wmz,
		},
		mime_type.ApplicationXMsXbap: {
			Xbap,
		},
		mime_type.ApplicationXMsaccess: {
			Mdb,
		},
		mime_type.ApplicationXMsbinder: {
			Obd,
		},
		mime_type.ApplicationXMscardfile: {
			Crd,
		},
		mime_type.ApplicationXMsclip: {
			Clp,
		},
		mime_type.ApplicationXMsdownload: {
			Exe,
		},
		mime_type.ApplicationXMsmediaview: {
			Mvb,
		},
		mime_type.ApplicationXMsmetafile: {
			Wmf,
		},
		mime_type.ApplicationXMsmoney: {
			Mny,
		},
		mime_type.ApplicationXMspublisher: {
			Pub,
		},
		mime_type.ApplicationXMsschedule: {
			Scd,
		},
		mime_type.ApplicationXMsterminal: {
			Trm,
		},
		mime_type.ApplicationXMswrite: {
			Wri,
		},
		mime_type.ApplicationXNetcdf: {
			Nc,
		},
		mime_type.ApplicationXPkcs12: {
			P12,
		},
		mime_type.ApplicationXPkcs7Certificates: {
			P7b,
		},
		mime_type.ApplicationXPkcs7Certreqresp: {
			P7r,
		},
		mime_type.ApplicationXSh: {
			Sh,
		},
		mime_type.ApplicationXShar: {
			Shar,
		},
		mime_type.ApplicationXShockwaveFlash: {
			Swf,
		},
		mime_type.ApplicationXSilverlightApp: {
			Xap,
		},
		mime_type.ApplicationXStuffit: {
			Sit,
		},
		mime_type.ApplicationXStuffitx: {
			Sitx,
		},
		mime_type.ApplicationXSv4cpio: {
			Sv4cpio,
		},
		mime_type.ApplicationXSv4crc: {
			Sv4crc,
		},
		mime_type.ApplicationXTar: {
			Tar,
		},
		mime_type.ApplicationXTcl: {
			Tcl,
		},
		mime_type.ApplicationXTex: {
			Tex,
		},
		mime_type.ApplicationXTexTfm: {
			Tfm,
		},
		mime_type.ApplicationXTexinfo: {
			Texinfo,
		},
		mime_type.ApplicationXUstar: {
			Ustar,
		},
		mime_type.ApplicationXWaisSource: {
			Src,
		},
		mime_type.ApplicationXX509CaCert: {
			Der,
		},
		mime_type.ApplicationXXfig: {
			Fig,
		},
		mime_type.ApplicationXXpinstall: {
			Xpi,
		},
		mime_type.ApplicationXYaml: {
			Yaml,
			Yml,
		},
		mime_type.ApplicationXcapDiffXml: {
			Xdf,
		},
		mime_type.ApplicationXencXml: {
			Xenc,
		},
		mime_type.ApplicationXhtmlXml: {
			Xhtml,
		},
		mime_type.ApplicationXml: {
			Xml,
		},
		mime_type.ApplicationXmlDtd: {
			Dtd,
		},
		mime_type.ApplicationXopXml: {
			Xop,
		},
		mime_type.ApplicationXsltXml: {
			Xslt,
		},
		mime_type.ApplicationXspfXml: {
			Xspf,
		},
		mime_type.ApplicationXvXml: {
			Mxml,
		},
		mime_type.ApplicationYang: {
			Yang,
		},
		mime_type.ApplicationYinXml: {
			Yin,
		},
		mime_type.ApplicationZip: {
			Zip,
		},
		mime_type.AudioAdpcm: {
			Adp,
		},
		mime_type.AudioBasic: {
			Au,
		},
		mime_type.AudioMidi: {
			Mid,
			Midi,
		},
		mime_type.AudioMp4: {
			Mp4a,
		},
		mime_type.AudioMpeg: {
			Mpga,
		},
		mime_type.AudioOgg: {
			Oga,
		},
		mime_type.AudioOpus: {
			Opus,
		},
		mime_type.AudioVndDeceAudio: {
			Uva,
		},
		mime_type.AudioVndDigitalWinds: {
			Eol,
		},
		mime_type.AudioVndDra: {
			Dra,
		},
		mime_type.AudioVndDts: {
			Dts,
		},
		mime_type.AudioVndDtsHd: {
			Dtshd,
		},
		mime_type.AudioVndLucentVoice: {
			Lvp,
		},
		mime_type.AudioVndMsPlayreadyMediaPya: {
			Pya,
		},
		mime_type.AudioVndNueraEcelp4800: {
			Ecelp4800,
		},
		mime_type.AudioVndNueraEcelp7470: {
			Ecelp7470,
		},
		mime_type.AudioVndNueraEcelp9600: {
			Ecelp9600,
		},
		mime_type.AudioVndRip: {
			Rip,
		},
		mime_type.AudioWav: {
			Wav,
		},
		mime_type.AudioWebm: {
			Weba,
		},
		mime_type.AudioXAac: {
			Aac,
		},
		mime_type.AudioXAiff: {
			Aif,
		},
		mime_type.AudioXMpegurl: {
			M3u,
		},
		mime_type.AudioXMsWax: {
			Wax,
		},
		mime_type.AudioXMsWma: {
			Wma,
		},
		mime_type.AudioXPnRealaudio: {
			Ram,
		},
		mime_type.AudioXPnRealaudioPlugin: {
			Rmp,
		},
		mime_type.ChemicalXCdx: {
			Cdx,
		},
		mime_type.ChemicalXCif: {
			Cif,
		},
		mime_type.ChemicalXCmdf: {
			Cmdf,
		},
		mime_type.ChemicalXCml: {
			Cml,
		},
		mime_type.ChemicalXCsml: {
			Csml,
		},
		mime_type.ChemicalXXyz: {
			Xyz,
		},
		mime_type.FontOtf: {
			Otf,
		},
		mime_type.FontTtf: {
			Ttf,
		},
		mime_type.FontWoff: {
			Woff,
		},
		mime_type.FontWoff2: {
			Woff2,
		},
		mime_type.ImageBmp: {
			Bmp,
		},
		mime_type.ImageCgm: {
			Cgm,
		},
		mime_type.ImageG3fax: {
			G3,
		},
		mime_type.ImageGif: {
			Gif,
		},
		mime_type.ImageIef: {
			Ief,
		},
		mime_type.ImageJpeg: {
			Jpeg,
			Jpg,
		},
		mime_type.ImageKtx: {
			Ktx,
		},
		mime_type.ImagePjpeg: {
			Pjpeg,
		},
		mime_type.ImagePng: {
			Png,
		},
		mime_type.ImagePrsBtif: {
			Btif,
		},
		mime_type.ImageSvgXml: {
			Svg,
		},
		mime_type.ImageTiff: {
			Tif,
			Tiff,
		},
		mime_type.ImageVndAdobePhotoshop: {
			Psd,
		},
		mime_type.ImageVndDeceGraphic: {
			Uvi,
		},
		mime_type.ImageVndDjvu: {
			Djvu,
		},
		mime_type.ImageVndDvbSubtitle: {
			Sub,
		},
		mime_type.ImageVndDwg: {
			Dwg,
		},
		mime_type.ImageVndDxf: {
			Dxf,
		},
		mime_type.ImageVndFastbidsheet: {
			Fbs,
		},
		mime_type.ImageVndFpx: {
			Fpx,
		},
		mime_type.ImageVndFst: {
			Fst,
		},
		mime_type.ImageVndFujixeroxEdmicsMmr: {
			Mmr,
		},
		mime_type.ImageVndFujixeroxEdmicsRlc: {
			Rlc,
		},
		mime_type.ImageVndMsModi: {
			Mdi,
		},
		mime_type.ImageVndNetFpx: {
			Npx,
		},
		mime_type.ImageVndWapWbmp: {
			Wbmp,
		},
		mime_type.ImageVndXiff: {
			Xif,
		},
		mime_type.ImageWebp: {
			Webp,
		},
		mime_type.ImageXCmuRaster: {
			Ras,
		},
		mime_type.ImageXCmx: {
			Cmx,
		},
		mime_type.ImageXFreehand: {
			Fh,
		},
		mime_type.ImageXIcon: {
			Ico,
		},
		mime_type.ImageXPcx: {
			Pcx,
		},
		mime_type.ImageXPict: {
			Pic,
		},
		mime_type.ImageXPortableAnymap: {
			Pnm,
		},
		mime_type.ImageXPortableBitmap: {
			Pbm,
		},
		mime_type.ImageXPortableGraymap: {
			Pgm,
		},
		mime_type.ImageXPortablePixmap: {
			Ppm,
		},
		mime_type.ImageXRgb: {
			Rgb,
		},
		mime_type.ImageXXbitmap: {
			Xbm,
		},
		mime_type.ImageXXpixmap: {
			Xpm,
		},
		mime_type.ImageXXwindowdump: {
			Xwd,
		},
		mime_type.MessageRfc822: {
			Eml,
		},
		mime_type.ModelIges: {
			Igs,
		},
		mime_type.ModelMesh: {
			Msh,
		},
		mime_type.ModelVndColladaXml: {
			Dae,
		},
		mime_type.ModelVndDwf: {
			Dwf,
		},
		mime_type.ModelVndGdl: {
			Gdl,
		},
		mime_type.ModelVndGtw: {
			Gtw,
		},
		mime_type.ModelVndMts: {
			Mts,
		},
		mime_type.ModelVndVtu: {
			Vtu,
		},
		mime_type.ModelVrml: {
			Wrl,
		},
		mime_type.TextCalendar: {
			Ics,
		},
		mime_type.TextCss: {
			Css,
		},
		mime_type.TextCsv: {
			Csv,
		},
		mime_type.TextHtml: {
			Html,
		},
		mime_type.TextN3: {
			N3,
		},
		mime_type.TextPlain: {
			Txt,
		},
		mime_type.TextPlainBas: {
			Par,
		},
		mime_type.TextPrsLinesTag: {
			Dsc,
		},
		mime_type.TextRichtext: {
			Rtx,
		},
		mime_type.TextSgml: {
			Sgml,
		},
		mime_type.TextTabSeparatedValues: {
			Tsv,
		},
		mime_type.TextTroff: {
			T,
		},
		mime_type.TextTurtle: {
			Ttl,
		},
		mime_type.TextUriList: {
			Uri,
		},
		mime_type.TextVndCurl: {
			Curl,
		},
		mime_type.TextVndCurlDcurl: {
			Dcurl,
		},
		mime_type.TextVndCurlMcurl: {
			Mcurl,
		},
		mime_type.TextVndCurlScurl: {
			Scurl,
		},
		mime_type.TextVndFly: {
			Fly,
		},
		mime_type.TextVndFmiFlexstor: {
			Flx,
		},
		mime_type.TextVndGraphviz: {
			Gv,
		},
		mime_type.TextVndIn3d3dml: {
			_3dml,
		},
		mime_type.TextVndIn3dSpot: {
			Spot,
		},
		mime_type.TextVndSunJ2meAppDescriptor: {
			Jad,
		},
		mime_type.TextVndWapWml: {
			Wml,
		},
		mime_type.TextVndWapWmlscript: {
			Wmls,
		},
		mime_type.TextXAsm: {
			S,
		},
		mime_type.TextXC: {
			C,
		},
		mime_type.TextXFortran: {
			F,
		},
		mime_type.TextXJavaSource: {
			Java,
		},
		mime_type.TextXPascal: {
			P,
		},
		mime_type.TextXSetext: {
			Etx,
		},
		mime_type.TextXUuencode: {
			Uu,
		},
		mime_type.TextXVcalendar: {
			Vcs,
		},
		mime_type.TextXVcard: {
			Vcf,
		},
		mime_type.Unkown: {},
		mime_type.Video3gpp: {
			_3gp,
		},
		mime_type.Video3gpp2: {
			_3g2,
		},
		mime_type.VideoH261: {
			H261,
		},
		mime_type.VideoH263: {
			H263,
		},
		mime_type.VideoH264: {
			H264,
		},
		mime_type.VideoJpeg: {
			Jpgv,
		},
		mime_type.VideoJpm: {
			Jpm,
		},
		mime_type.VideoMj2: {
			Mj2,
		},
		mime_type.VideoMp2t: {
			Ts,
		},
		mime_type.VideoMp4: {
			Mp4,
		},
		mime_type.VideoMpeg: {
			Mpeg,
		},
		mime_type.VideoOgg: {
			Ogv,
		},
		mime_type.VideoQuicktime: {
			Qt,
		},
		mime_type.VideoVndDeceHd: {
			Uvh,
		},
		mime_type.VideoVndDeceMobile: {
			Uvm,
		},
		mime_type.VideoVndDecePd: {
			Uvp,
		},
		mime_type.VideoVndDeceSd: {
			Uvs,
		},
		mime_type.VideoVndDeceVideo: {
			Uvv,
		},
		mime_type.VideoVndFvt: {
			Fvt,
		},
		mime_type.VideoVndMpegurl: {
			Mxu,
		},
		mime_type.VideoVndMsPlayreadyMediaPyv: {
			Pyv,
		},
		mime_type.VideoVndUvvuMp4: {
			Uvu,
		},
		mime_type.VideoVndVivo: {
			Viv,
		},
		mime_type.VideoWebm: {
			Webm,
		},
		mime_type.VideoXF4v: {
			F4v,
		},
		mime_type.VideoXFli: {
			Fli,
		},
		mime_type.VideoXFlv: {
			Flv,
		},
		mime_type.VideoXM4v: {
			M4v,
		},
		mime_type.VideoXMsAsf: {
			Asf,
		},
		mime_type.VideoXMsWm: {
			Wm,
		},
		mime_type.VideoXMsWmv: {
			Wmv,
		},
		mime_type.VideoXMsWmx: {
			Wmx,
		},
		mime_type.VideoXMsWvx: {
			Wvx,
		},
		mime_type.VideoXMsvideo: {
			Avi,
		},
		mime_type.VideoXSgiMovie: {
			Movie,
		},
		mime_type.XConferenceXCooltalk: {
			Ice,
		},
		mime_type.ApplicationToml: {
			Toml,
		},
		mime_type.ApplicationHcl: {
			Hcl,
		},
		mime_type.ApplicationIni: {
			Ini,
		},
	}
)
